// Shared business logic + vocab data for the Hanzi Cards flashcard app.
// Plain ES module — no npm imports, no DOM access at module scope.

export const SEED = [
  { hanzi:"你好", pinyin:"nǐ hǎo", meaning:"hello" },
  { hanzi:"谢谢", pinyin:"xiè xiè", meaning:"thank you" },
  { hanzi:"朋友", pinyin:"péng yǒu", meaning:"friend" },
  { hanzi:"学习", pinyin:"xué xí", meaning:"to study" },
  { hanzi:"时间", pinyin:"shí jiān", meaning:"time" },
  { hanzi:"明天", pinyin:"míng tiān", meaning:"tomorrow" },
  { hanzi:"喜欢", pinyin:"xǐ huān", meaning:"to like" },
  { hanzi:"工作", pinyin:"gōng zuò", meaning:"work / job" },
];

export const IMPORT_BATCH_1 = [
  { hanzi:"我", pinyin:"wǒ", meaning:"I / me" },
  { hanzi:"你", pinyin:"nǐ", meaning:"you" },
  { hanzi:"他", pinyin:"tā", meaning:"he / him" },
  { hanzi:"她", pinyin:"tā", meaning:"she / her" },
  { hanzi:"它", pinyin:"tā", meaning:"it" },
  { hanzi:"的", pinyin:"de", meaning:"possessive particle ('s)" },
  { hanzi:"个", pinyin:"gè", meaning:"measure word (general)" },
  { hanzi:"人", pinyin:"rén", meaning:"person" },
  { hanzi:"是", pinyin:"shì", meaning:"to be" },
  { hanzi:"不", pinyin:"bù", meaning:"not / no" },
  { hanzi:"爱", pinyin:"ài", meaning:"love" },
  { hanzi:"一", pinyin:"yī", meaning:"one" },
  { hanzi:"早", pinyin:"zǎo", meaning:"early / morning" },
  { hanzi:"晚", pinyin:"wǎn", meaning:"late / evening" },
  { hanzi:"安", pinyin:"ān", meaning:"peace / safe" },
  { hanzi:"早安", pinyin:"zǎo ān", meaning:"good morning" },
  { hanzi:"晚安", pinyin:"wǎn ān", meaning:"good night" },
  { hanzi:"在", pinyin:"zài", meaning:"at / in / located" },
  { hanzi:"了", pinyin:"le", meaning:"completed-action particle" },
  { hanzi:"们", pinyin:"men", meaning:"plural marker (we/they)" },
  { hanzi:"有", pinyin:"yǒu", meaning:"to have" },
  { hanzi:"大", pinyin:"dà", meaning:"big" },
  { hanzi:"之", pinyin:"zhī", meaning:"possessive particle (formal)" },
  { hanzi:"这", pinyin:"zhè", meaning:"this" },
  { hanzi:"为", pinyin:"weì", meaning:"for / because of" },
  { hanzi:"日", pinyin:"rì", meaning:"day / sun" },
  { hanzi:"好", pinyin:"hǎo", meaning:"good" },
  { hanzi:"太阳", pinyin:"tài-yáng", meaning:"sun" },
  { hanzi:"月", pinyin:"yuè", meaning:"moon / month" },
  { hanzi:"那", pinyin:"nà", meaning:"that" },
  { hanzi:"谁", pinyin:"shéi", meaning:"who" },
  { hanzi:"室友", pinyin:"shì-yǒu", meaning:"roommate" },
  { hanzi:"老师", pinyin:"lǎo-shī", meaning:"teacher" },
  { hanzi:"男朋友", pinyin:"nán péng-yǒu", meaning:"boyfriend" },
  { hanzi:"女朋友", pinyin:"nü péng-yǒu", meaning:"girlfriend" },
  { hanzi:"名字", pinyin:"míng-zì", meaning:"name" },
  { hanzi:"叫", pinyin:"jiào", meaning:"to be called" },
  { hanzi:"是的", pinyin:"shì de", meaning:"yes / that's right" },
  { hanzi:"什么", pinyin:"shí-me", meaning:"what" },
  { hanzi:"请", pinyin:"qǐng", meaning:"please" },
  { hanzi:"问", pinyin:"wèn", meaning:"to ask" },
  { hanzi:"请问", pinyin:"qǐng wèn", meaning:"excuse me / may I ask" },
  { hanzi:"对不起", pinyin:"duì-bù-qì", meaning:"sorry" },
  { hanzi:"没关系", pinyin:"méi-guān-xì", meaning:"it's okay / no problem" },
  { hanzi:"同学", pinyin:"tóng-xué", meaning:"classmate" },
  { hanzi:"不客气", pinyin:"bù kè qì", meaning:"you're welcome" },
  { hanzi:"谢谢", pinyin:"xiè-xiè", meaning:"thank you" },
  { hanzi:"快乐", pinyin:"kuài-lè", meaning:"happy" },
  { hanzi:"米饭", pinyin:"mǐ fàn", meaning:"cooked rice" },
  { hanzi:"好的", pinyin:"hǎo de", meaning:"okay / sounds good" },
  { hanzi:"火", pinyin:"huo", meaning:"fire" },
  { hanzi:"水", pinyin:"shuǐ", meaning:"water" },
  { hanzi:"篮球", pinyin:"lán-qiú", meaning:"basketball" },
  { hanzi:"龙", pinyin:"lóng", meaning:"dragon" },
  { hanzi:"恐龙", pinyin:"kǒng-lóng", meaning:"dinosaur" },
  { hanzi:"月亮", pinyin:"yuè-liàng", meaning:"moon" },
  { hanzi:"学生", pinyin:"xué-shēng", meaning:"student" },
  { hanzi:"高兴", pinyin:"gão-shìng", meaning:"happy / glad" },
  { hanzi:"很", pinyin:"hěn", meaning:"very" },
  { hanzi:"会说", pinyin:"huì shuō", meaning:"can speak" },
  { hanzi:"对", pinyin:"duì", meaning:"correct / right" },
  { hanzi:"家", pinyin:"jiā", meaning:"home / family" },
  { hanzi:"口人", pinyin:"kǒu rén", meaning:"members of the family (measure)" },
  { hanzi:"和", pinyin:"hé", meaning:"and" },
  { hanzi:"年", pinyin:"nián", meaning:"year" },
];

export const EXTRA_DICT = [
  { hanzi:"妈妈", pinyin:"māma", meaning:"mom" },
  { hanzi:"爸爸", pinyin:"bàba", meaning:"dad" },
  { hanzi:"儿子", pinyin:"érzi", meaning:"son" },
  { hanzi:"女儿", pinyin:"nǚ'ér", meaning:"daughter" },
  { hanzi:"猫", pinyin:"māo", meaning:"cat" },
  { hanzi:"狗", pinyin:"gǒu", meaning:"dog" },
  { hanzi:"书", pinyin:"shū", meaning:"book" },
  { hanzi:"笔", pinyin:"bǐ", meaning:"pen" },
  { hanzi:"桌子", pinyin:"zhuōzi", meaning:"table" },
  { hanzi:"椅子", pinyin:"yǐzi", meaning:"chair" },
  { hanzi:"车", pinyin:"chē", meaning:"car" },
  { hanzi:"飞机", pinyin:"fēijī", meaning:"airplane" },
  { hanzi:"火车", pinyin:"huǒchē", meaning:"train" },
  { hanzi:"自行车", pinyin:"zìxíngchē", meaning:"bicycle" },
  { hanzi:"学校", pinyin:"xuéxiào", meaning:"school" },
  { hanzi:"医院", pinyin:"yīyuàn", meaning:"hospital" },
  { hanzi:"商店", pinyin:"shāngdiàn", meaning:"store" },
  { hanzi:"公司", pinyin:"gōngsī", meaning:"company" },
  { hanzi:"电话", pinyin:"diànhuà", meaning:"phone" },
  { hanzi:"电脑", pinyin:"diànnǎo", meaning:"computer" },
  { hanzi:"电视", pinyin:"diànshì", meaning:"television" },
  { hanzi:"手机", pinyin:"shǒujī", meaning:"cell phone" },
  { hanzi:"衣服", pinyin:"yīfu", meaning:"clothes" },
  { hanzi:"鞋", pinyin:"xié", meaning:"shoes" },
  { hanzi:"钱", pinyin:"qián", meaning:"money" },
  { hanzi:"今天", pinyin:"jīntiān", meaning:"today" },
  { hanzi:"昨天", pinyin:"zuótiān", meaning:"yesterday" },
  { hanzi:"明天", pinyin:"míngtiān", meaning:"tomorrow" },
  { hanzi:"现在", pinyin:"xiànzài", meaning:"now" },
  { hanzi:"星期", pinyin:"xīngqī", meaning:"week" },
  { hanzi:"早上", pinyin:"zǎoshang", meaning:"morning" },
  { hanzi:"晚上", pinyin:"wǎnshang", meaning:"evening" },
  { hanzi:"中午", pinyin:"zhōngwǔ", meaning:"noon" },
  { hanzi:"吃", pinyin:"chī", meaning:"to eat" },
  { hanzi:"喝", pinyin:"hē", meaning:"to drink" },
  { hanzi:"睡觉", pinyin:"shuìjiào", meaning:"to sleep" },
  { hanzi:"看", pinyin:"kàn", meaning:"to look / watch" },
  { hanzi:"听", pinyin:"tīng", meaning:"to listen" },
  { hanzi:"走", pinyin:"zǒu", meaning:"to walk" },
  { hanzi:"跑", pinyin:"pǎo", meaning:"to run" },
  { hanzi:"跳", pinyin:"tiào", meaning:"to jump" },
  { hanzi:"笑", pinyin:"xiào", meaning:"to laugh" },
  { hanzi:"哭", pinyin:"kū", meaning:"to cry" },
  { hanzi:"高", pinyin:"gāo", meaning:"tall" },
  { hanzi:"矮", pinyin:"ǎi", meaning:"short (height)" },
  { hanzi:"胖", pinyin:"pàng", meaning:"fat" },
  { hanzi:"瘦", pinyin:"shòu", meaning:"thin" },
  { hanzi:"漂亮", pinyin:"piàoliang", meaning:"pretty" },
  { hanzi:"帅", pinyin:"shuài", meaning:"handsome" },
  { hanzi:"新", pinyin:"xīn", meaning:"new" },
  { hanzi:"旧", pinyin:"jiù", meaning:"old (object)" },
  { hanzi:"多", pinyin:"duō", meaning:"many / much" },
  { hanzi:"少", pinyin:"shǎo", meaning:"few / little" },
  { hanzi:"冷", pinyin:"lěng", meaning:"cold" },
  { hanzi:"热", pinyin:"rè", meaning:"hot" },
  { hanzi:"天气", pinyin:"tiānqì", meaning:"weather" },
  { hanzi:"下雨", pinyin:"xiàyǔ", meaning:"to rain" },
  { hanzi:"颜色", pinyin:"yánsè", meaning:"color" },
  { hanzi:"红色", pinyin:"hóngsè", meaning:"red" },
  { hanzi:"黑色", pinyin:"hēisè", meaning:"black" },
  { hanzi:"白色", pinyin:"báisè", meaning:"white" },
  { hanzi:"蓝色", pinyin:"lánsè", meaning:"blue" },
  { hanzi:"绿色", pinyin:"lǜsè", meaning:"green" },
  { hanzi:"黄色", pinyin:"huángsè", meaning:"yellow" },
];

export const EXTRA_DICT2 = [
  { hanzi:"二", pinyin:"èr", meaning:"two" },
  { hanzi:"三", pinyin:"sān", meaning:"three" },
  { hanzi:"四", pinyin:"sì", meaning:"four" },
  { hanzi:"五", pinyin:"wǔ", meaning:"five" },
  { hanzi:"六", pinyin:"liù", meaning:"six" },
  { hanzi:"七", pinyin:"qī", meaning:"seven" },
  { hanzi:"八", pinyin:"bā", meaning:"eight" },
  { hanzi:"九", pinyin:"jiǔ", meaning:"nine" },
  { hanzi:"十", pinyin:"shí", meaning:"ten" },
  { hanzi:"零", pinyin:"líng", meaning:"zero" },
  { hanzi:"百", pinyin:"bǎi", meaning:"hundred" },
  { hanzi:"千", pinyin:"qiān", meaning:"thousand" },
  { hanzi:"万", pinyin:"wàn", meaning:"ten thousand" },
  { hanzi:"星期一", pinyin:"xīngqīyī", meaning:"Monday" },
  { hanzi:"星期二", pinyin:"xīngqīèr", meaning:"Tuesday" },
  { hanzi:"星期三", pinyin:"xīngqīsān", meaning:"Wednesday" },
  { hanzi:"星期四", pinyin:"xīngqīsì", meaning:"Thursday" },
  { hanzi:"星期五", pinyin:"xīngqīwǔ", meaning:"Friday" },
  { hanzi:"星期六", pinyin:"xīngqīliù", meaning:"Saturday" },
  { hanzi:"星期天", pinyin:"xīngqītiān", meaning:"Sunday" },
  { hanzi:"上", pinyin:"shàng", meaning:"up / on" },
  { hanzi:"下", pinyin:"xià", meaning:"down / under" },
  { hanzi:"左", pinyin:"zuǒ", meaning:"left" },
  { hanzi:"右", pinyin:"yòu", meaning:"right" },
  { hanzi:"前", pinyin:"qián", meaning:"front / before" },
  { hanzi:"后", pinyin:"hòu", meaning:"back / after" },
  { hanzi:"里", pinyin:"lǐ", meaning:"inside" },
  { hanzi:"外", pinyin:"wài", meaning:"outside" },
  { hanzi:"东", pinyin:"dōng", meaning:"east" },
  { hanzi:"西", pinyin:"xī", meaning:"west" },
  { hanzi:"南", pinyin:"nán", meaning:"south" },
  { hanzi:"北", pinyin:"běi", meaning:"north" },
  { hanzi:"中国", pinyin:"zhōngguó", meaning:"China" },
  { hanzi:"国家", pinyin:"guójiā", meaning:"country" },
  { hanzi:"城市", pinyin:"chéngshì", meaning:"city" },
  { hanzi:"头", pinyin:"tóu", meaning:"head" },
  { hanzi:"眼睛", pinyin:"yǎnjīng", meaning:"eyes" },
  { hanzi:"耳朵", pinyin:"ěrduo", meaning:"ears" },
  { hanzi:"鼻子", pinyin:"bízi", meaning:"nose" },
  { hanzi:"嘴", pinyin:"zuǐ", meaning:"mouth" },
  { hanzi:"手", pinyin:"shǒu", meaning:"hand" },
  { hanzi:"脚", pinyin:"jiǎo", meaning:"foot" },
  { hanzi:"心", pinyin:"xīn", meaning:"heart" },
  { hanzi:"去", pinyin:"qù", meaning:"to go" },
  { hanzi:"来", pinyin:"lái", meaning:"to come" },
  { hanzi:"说", pinyin:"shuō", meaning:"to speak" },
  { hanzi:"写", pinyin:"xiě", meaning:"to write" },
  { hanzi:"读", pinyin:"dú", meaning:"to read" },
  { hanzi:"买", pinyin:"mǎi", meaning:"to buy" },
  { hanzi:"卖", pinyin:"mài", meaning:"to sell" },
  { hanzi:"给", pinyin:"gěi", meaning:"to give" },
  { hanzi:"做", pinyin:"zuò", meaning:"to do / make" },
  { hanzi:"坐", pinyin:"zuò", meaning:"to sit" },
  { hanzi:"站", pinyin:"zhàn", meaning:"to stand" },
  { hanzi:"开", pinyin:"kāi", meaning:"to open" },
  { hanzi:"关", pinyin:"guān", meaning:"to close" },
  { hanzi:"穿", pinyin:"chuān", meaning:"to wear" },
  { hanzi:"用", pinyin:"yòng", meaning:"to use" },
  { hanzi:"玩", pinyin:"wán", meaning:"to play" },
  { hanzi:"唱歌", pinyin:"chànggē", meaning:"to sing" },
  { hanzi:"跳舞", pinyin:"tiàowǔ", meaning:"to dance" },
  { hanzi:"休息", pinyin:"xiūxi", meaning:"to rest" },
  { hanzi:"帮助", pinyin:"bāngzhù", meaning:"to help" },
  { hanzi:"长", pinyin:"cháng", meaning:"long" },
  { hanzi:"短", pinyin:"duǎn", meaning:"short (length)" },
  { hanzi:"快", pinyin:"kuài", meaning:"fast" },
  { hanzi:"慢", pinyin:"màn", meaning:"slow" },
  { hanzi:"贵", pinyin:"guì", meaning:"expensive" },
  { hanzi:"便宜", pinyin:"piányi", meaning:"cheap" },
  { hanzi:"干净", pinyin:"gānjìng", meaning:"clean" },
  { hanzi:"脏", pinyin:"zāng", meaning:"dirty" },
  { hanzi:"容易", pinyin:"róngyì", meaning:"easy" },
  { hanzi:"难", pinyin:"nán", meaning:"difficult" },
  { hanzi:"忙", pinyin:"máng", meaning:"busy" },
  { hanzi:"累", pinyin:"lèi", meaning:"tired" },
  { hanzi:"饿", pinyin:"è", meaning:"hungry" },
  { hanzi:"渴", pinyin:"kě", meaning:"thirsty" },
  { hanzi:"怎么", pinyin:"zěnme", meaning:"how" },
  { hanzi:"为什么", pinyin:"wèishénme", meaning:"why" },
  { hanzi:"哪", pinyin:"nǎ", meaning:"which" },
  { hanzi:"哪里", pinyin:"nǎlǐ", meaning:"where" },
  { hanzi:"多少", pinyin:"duōshǎo", meaning:"how many / much" },
  { hanzi:"几", pinyin:"jǐ", meaning:"how many (small numbers)" },
  { hanzi:"房子", pinyin:"fángzi", meaning:"house" },
  { hanzi:"房间", pinyin:"fángjiān", meaning:"room" },
  { hanzi:"门", pinyin:"mén", meaning:"door" },
  { hanzi:"窗户", pinyin:"chuānghu", meaning:"window" },
  { hanzi:"床", pinyin:"chuáng", meaning:"bed" },
  { hanzi:"饭", pinyin:"fàn", meaning:"meal / rice" },
  { hanzi:"菜", pinyin:"cài", meaning:"dish / vegetable" },
  { hanzi:"茶", pinyin:"chá", meaning:"tea" },
  { hanzi:"咖啡", pinyin:"kāfēi", meaning:"coffee" },
  { hanzi:"牛奶", pinyin:"niúnǎi", meaning:"milk" },
  { hanzi:"面包", pinyin:"miànbāo", meaning:"bread" },
  { hanzi:"苹果", pinyin:"píngguǒ", meaning:"apple" },
  { hanzi:"香蕉", pinyin:"xiāngjiāo", meaning:"banana" },
  { hanzi:"西瓜", pinyin:"xīguā", meaning:"watermelon" },
];

export const IMPORT_BATCH_HSK1 = [
  { hanzi:"我", pinyin:"wǒ", meaning:"I / me" },
  { hanzi:"我们", pinyin:"wǒmen", meaning:"we / us" },
  { hanzi:"你", pinyin:"nǐ", meaning:"you" },
  { hanzi:"你们", pinyin:"nǐmen", meaning:"you (plural)" },
  { hanzi:"他", pinyin:"tā", meaning:"he / him" },
  { hanzi:"她", pinyin:"tā", meaning:"she / her" },
  { hanzi:"他们", pinyin:"tāmen", meaning:"they (mixed / male)" },
  { hanzi:"她们", pinyin:"tāmen", meaning:"they (female)" },
  { hanzi:"这", pinyin:"zhè", meaning:"this" },
  { hanzi:"那", pinyin:"nà", meaning:"that" },
  { hanzi:"哪", pinyin:"nǎ", meaning:"which / where" },
  { hanzi:"谁", pinyin:"shéi", meaning:"who" },
  { hanzi:"什么", pinyin:"shénme", meaning:"what" },
  { hanzi:"多少", pinyin:"duōshǎo", meaning:"how many / how much" },
  { hanzi:"几", pinyin:"jǐ", meaning:"how many (small numbers)" },
  { hanzi:"怎么", pinyin:"zěnme", meaning:"how" },
  { hanzi:"怎么样", pinyin:"zěnmeyàng", meaning:"how is it / how about" },
  { hanzi:"一", pinyin:"yī", meaning:"one" },
  { hanzi:"二", pinyin:"èr", meaning:"two" },
  { hanzi:"三", pinyin:"sān", meaning:"three" },
  { hanzi:"四", pinyin:"sì", meaning:"four" },
  { hanzi:"五", pinyin:"wǔ", meaning:"five" },
  { hanzi:"六", pinyin:"liù", meaning:"six" },
  { hanzi:"七", pinyin:"qī", meaning:"seven" },
  { hanzi:"八", pinyin:"bā", meaning:"eight" },
  { hanzi:"九", pinyin:"jiǔ", meaning:"nine" },
  { hanzi:"十", pinyin:"shí", meaning:"ten" },
  { hanzi:"零", pinyin:"líng", meaning:"zero" },
  { hanzi:"个", pinyin:"gè", meaning:"measure word (general)" },
  { hanzi:"岁", pinyin:"suì", meaning:"years old (age)" },
  { hanzi:"本", pinyin:"běn", meaning:"measure word for books" },
  { hanzi:"些", pinyin:"xiē", meaning:"some / a few" },
  { hanzi:"块", pinyin:"kuài", meaning:"piece / dollar (money)" },
  { hanzi:"不", pinyin:"bù", meaning:"not / no" },
  { hanzi:"没", pinyin:"méi", meaning:"not / haven't" },
  { hanzi:"很", pinyin:"hěn", meaning:"very" },
  { hanzi:"太", pinyin:"tài", meaning:"too (excessively)" },
  { hanzi:"都", pinyin:"dōu", meaning:"all / both" },
  { hanzi:"和", pinyin:"hé", meaning:"and" },
  { hanzi:"在", pinyin:"zài", meaning:"at / in" },
  { hanzi:"的", pinyin:"de", meaning:"possessive particle" },
  { hanzi:"了", pinyin:"le", meaning:"completed-action particle" },
  { hanzi:"吗", pinyin:"ma", meaning:"question particle" },
  { hanzi:"呢", pinyin:"ne", meaning:"question particle" },
  { hanzi:"喂", pinyin:"wèi", meaning:"hello (on the phone)" },
  { hanzi:"家", pinyin:"jiā", meaning:"home / family" },
  { hanzi:"学校", pinyin:"xuéxiào", meaning:"school" },
  { hanzi:"饭店", pinyin:"fàndiàn", meaning:"restaurant" },
  { hanzi:"商店", pinyin:"shāngdiàn", meaning:"store" },
  { hanzi:"医院", pinyin:"yīyuàn", meaning:"hospital" },
  { hanzi:"火车站", pinyin:"huǒchēzhàn", meaning:"train station" },
  { hanzi:"中国", pinyin:"zhōngguó", meaning:"China" },
  { hanzi:"北京", pinyin:"běijīng", meaning:"Beijing" },
  { hanzi:"上", pinyin:"shàng", meaning:"up / on" },
  { hanzi:"下", pinyin:"xià", meaning:"down / under" },
  { hanzi:"前面", pinyin:"qiánmiàn", meaning:"front" },
  { hanzi:"后面", pinyin:"hòumiàn", meaning:"behind" },
  { hanzi:"里", pinyin:"lǐ", meaning:"inside" },
  { hanzi:"今天", pinyin:"jīntiān", meaning:"today" },
  { hanzi:"明天", pinyin:"míngtiān", meaning:"tomorrow" },
  { hanzi:"昨天", pinyin:"zuótiān", meaning:"yesterday" },
  { hanzi:"上午", pinyin:"shàngwǔ", meaning:"morning" },
  { hanzi:"中午", pinyin:"zhōngwǔ", meaning:"noon" },
  { hanzi:"下午", pinyin:"xiàwǔ", meaning:"afternoon" },
  { hanzi:"年", pinyin:"nián", meaning:"year" },
  { hanzi:"月", pinyin:"yuè", meaning:"month" },
  { hanzi:"日", pinyin:"rì", meaning:"day" },
  { hanzi:"星期", pinyin:"xīngqī", meaning:"week" },
  { hanzi:"点", pinyin:"diǎn", meaning:"o'clock / dot" },
  { hanzi:"分钟", pinyin:"fēnzhōng", meaning:"minute" },
  { hanzi:"现在", pinyin:"xiànzài", meaning:"now" },
  { hanzi:"时候", pinyin:"shíhou", meaning:"time / moment" },
  { hanzi:"爸爸", pinyin:"bàba", meaning:"father" },
  { hanzi:"妈妈", pinyin:"māma", meaning:"mother" },
  { hanzi:"儿子", pinyin:"érzi", meaning:"son" },
  { hanzi:"女儿", pinyin:"nǚér", meaning:"daughter" },
  { hanzi:"老师", pinyin:"lǎoshī", meaning:"teacher" },
  { hanzi:"学生", pinyin:"xuéshēng", meaning:"student" },
  { hanzi:"同学", pinyin:"tóngxué", meaning:"classmate" },
  { hanzi:"朋友", pinyin:"péngyou", meaning:"friend" },
  { hanzi:"医生", pinyin:"yīshēng", meaning:"doctor" },
  { hanzi:"先生", pinyin:"xiānsheng", meaning:"mister / sir" },
  { hanzi:"小姐", pinyin:"xiǎojiě", meaning:"miss" },
  { hanzi:"衣服", pinyin:"yīfu", meaning:"clothes" },
  { hanzi:"水", pinyin:"shuǐ", meaning:"water" },
  { hanzi:"菜", pinyin:"cài", meaning:"vegetable / dish" },
  { hanzi:"米饭", pinyin:"mǐfàn", meaning:"cooked rice" },
  { hanzi:"水果", pinyin:"shuǐguǒ", meaning:"fruit" },
  { hanzi:"苹果", pinyin:"píngguǒ", meaning:"apple" },
  { hanzi:"茶", pinyin:"chá", meaning:"tea" },
  { hanzi:"杯子", pinyin:"bēizi", meaning:"cup" },
  { hanzi:"钱", pinyin:"qián", meaning:"money" },
  { hanzi:"飞机", pinyin:"fēijī", meaning:"airplane" },
  { hanzi:"出租车", pinyin:"chūzūchē", meaning:"taxi" },
  { hanzi:"电视", pinyin:"diànshì", meaning:"television" },
  { hanzi:"电脑", pinyin:"diànnǎo", meaning:"computer" },
  { hanzi:"电影", pinyin:"diànyǐng", meaning:"movie" },
  { hanzi:"天气", pinyin:"tiānqì", meaning:"weather" },
  { hanzi:"猫", pinyin:"māo", meaning:"cat" },
  { hanzi:"狗", pinyin:"gǒu", meaning:"dog" },
  { hanzi:"东西", pinyin:"dōngxi", meaning:"thing" },
  { hanzi:"人", pinyin:"rén", meaning:"person" },
  { hanzi:"名字", pinyin:"míngzi", meaning:"name" },
  { hanzi:"书", pinyin:"shū", meaning:"book" },
  { hanzi:"汉语", pinyin:"hànyǔ", meaning:"Chinese (language)" },
  { hanzi:"字", pinyin:"zì", meaning:"(written) character" },
  { hanzi:"桌子", pinyin:"zhuōzi", meaning:"desk" },
  { hanzi:"椅子", pinyin:"yǐzi", meaning:"chair" },
  { hanzi:"谢谢", pinyin:"xièxie", meaning:"thank you" },
  { hanzi:"不客气", pinyin:"búkèqì", meaning:"you're welcome" },
  { hanzi:"再见", pinyin:"zàijiàn", meaning:"goodbye" },
  { hanzi:"请", pinyin:"qǐng", meaning:"please" },
  { hanzi:"对不起", pinyin:"duìbùqǐ", meaning:"sorry" },
  { hanzi:"没关系", pinyin:"méiguānxì", meaning:"it doesn't matter" },
  { hanzi:"是", pinyin:"shì", meaning:"to be" },
  { hanzi:"有", pinyin:"yǒu", meaning:"to have" },
  { hanzi:"看", pinyin:"kàn", meaning:"to look / watch" },
  { hanzi:"听", pinyin:"tīng", meaning:"to listen" },
  { hanzi:"说话", pinyin:"shuōhuà", meaning:"to speak / talk" },
  { hanzi:"读", pinyin:"dú", meaning:"to read" },
  { hanzi:"写", pinyin:"xiě", meaning:"to write" },
  { hanzi:"看见", pinyin:"kànjiàn", meaning:"to see" },
  { hanzi:"叫", pinyin:"jiào", meaning:"to be called" },
  { hanzi:"来", pinyin:"lái", meaning:"to come" },
  { hanzi:"回", pinyin:"huí", meaning:"to return" },
  { hanzi:"去", pinyin:"qù", meaning:"to go" },
  { hanzi:"吃", pinyin:"chī", meaning:"to eat" },
  { hanzi:"喝", pinyin:"hē", meaning:"to drink" },
  { hanzi:"睡觉", pinyin:"shuìjiào", meaning:"to sleep" },
  { hanzi:"打电话", pinyin:"dǎ diànhuà", meaning:"to make a phone call" },
  { hanzi:"做", pinyin:"zuò", meaning:"to do" },
  { hanzi:"买", pinyin:"mǎi", meaning:"to buy" },
  { hanzi:"开", pinyin:"kāi", meaning:"to open" },
  { hanzi:"坐", pinyin:"zuò", meaning:"to sit" },
  { hanzi:"住", pinyin:"zhù", meaning:"to live / reside" },
  { hanzi:"学习", pinyin:"xuéxí", meaning:"to study" },
  { hanzi:"工作", pinyin:"gōngzuò", meaning:"to work" },
  { hanzi:"下雨", pinyin:"xiàyǔ", meaning:"to rain" },
  { hanzi:"爱", pinyin:"ài", meaning:"to love" },
  { hanzi:"喜欢", pinyin:"xǐhuan", meaning:"to like" },
  { hanzi:"想", pinyin:"xiǎng", meaning:"to want / to think" },
  { hanzi:"认识", pinyin:"rènshi", meaning:"to know (a person)" },
  { hanzi:"会", pinyin:"huì", meaning:"can / know how to" },
  { hanzi:"能", pinyin:"néng", meaning:"can / to be able to" },
  { hanzi:"好", pinyin:"hǎo", meaning:"good" },
  { hanzi:"大", pinyin:"dà", meaning:"big" },
  { hanzi:"小", pinyin:"xiǎo", meaning:"small" },
  { hanzi:"多", pinyin:"duō", meaning:"many / much" },
  { hanzi:"少", pinyin:"shǎo", meaning:"few / little" },
  { hanzi:"冷", pinyin:"lěng", meaning:"cold" },
  { hanzi:"热", pinyin:"rè", meaning:"hot" },
  { hanzi:"高兴", pinyin:"gāoxìng", meaning:"happy" },
  { hanzi:"漂亮", pinyin:"piàoliang", meaning:"beautiful" },
];

export const IMPORT_BATCH_HSK2 = [
  { hanzi:"您", pinyin:"nín", meaning:"you (polite)" },
  { hanzi:"它", pinyin:"tā", meaning:"it" },
  { hanzi:"大家", pinyin:"dàjiā", meaning:"everyone", literal:"big + family" },
  { hanzi:"每", pinyin:"měi", meaning:"every" },
  { hanzi:"为什么", pinyin:"wèishénme", meaning:"why", literal:"for + what" },
  { hanzi:"两", pinyin:"liǎng", meaning:"two (of something)" },
  { hanzi:"第一", pinyin:"dìyī", meaning:"first", literal:"ordinal marker + one" },
  { hanzi:"次", pinyin:"cì", meaning:"time / occurrence" },
  { hanzi:"公斤", pinyin:"gōngjīn", meaning:"kilogram", literal:"public + catty (unit)" },
  { hanzi:"元", pinyin:"yuán", meaning:"yuan (currency)" },
  { hanzi:"件", pinyin:"jiàn", meaning:"item (measure word)" },
  { hanzi:"张", pinyin:"zhāng", meaning:"sheet (measure word)" },
  { hanzi:"别", pinyin:"bié", meaning:"don't" },
  { hanzi:"非常", pinyin:"fēicháng", meaning:"very / extremely", literal:"not + ordinary" },
  { hanzi:"也", pinyin:"yě", meaning:"also / too" },
  { hanzi:"还", pinyin:"hái", meaning:"still / also" },
  { hanzi:"最", pinyin:"zuì", meaning:"most" },
  { hanzi:"真", pinyin:"zhēn", meaning:"really / truly" },
  { hanzi:"正在", pinyin:"zhèngzài", meaning:"in the middle of (doing)", literal:"just / precisely + at" },
  { hanzi:"已经", pinyin:"yǐjīng", meaning:"already", literal:"already + pass through" },
  { hanzi:"一起", pinyin:"yìqǐ", meaning:"together", literal:"one + rise / together" },
  { hanzi:"再", pinyin:"zài", meaning:"again" },
  { hanzi:"就", pinyin:"jiù", meaning:"then / right away" },
  { hanzi:"因为", pinyin:"yīnwèi", meaning:"because", literal:"reason + for" },
  { hanzi:"所以", pinyin:"suǒyǐ", meaning:"so / therefore", literal:"that which + by means of" },
  { hanzi:"但是", pinyin:"dànshì", meaning:"but", literal:"but + is" },
  { hanzi:"从", pinyin:"cóng", meaning:"from" },
  { hanzi:"此", pinyin:"cǐ", meaning:"this (formal)" },
  { hanzi:"向", pinyin:"xiàng", meaning:"towards" },
  { hanzi:"离", pinyin:"lí", meaning:"away from / distance to" },
  { hanzi:"得", pinyin:"de", meaning:"complement particle" },
  { hanzi:"着", pinyin:"zhe", meaning:"continuous-action particle" },
  { hanzi:"过", pinyin:"guo", meaning:"experiential-action particle" },
  { hanzi:"吧", pinyin:"ba", meaning:"suggestion particle" },
  { hanzi:"饭馆", pinyin:"fànguǎn", meaning:"restaurant", literal:"meal + establishment / hall" },
  { hanzi:"机场", pinyin:"jīchǎng", meaning:"airport", literal:"machine + field / place" },
  { hanzi:"教室", pinyin:"jiàoshì", meaning:"classroom", literal:"teach + room" },
  { hanzi:"房间", pinyin:"fángjiān", meaning:"room", literal:"house + between / space" },
  { hanzi:"路", pinyin:"lù", meaning:"road" },
  { hanzi:"左边", pinyin:"zuǒbiān", meaning:"left side", literal:"left + side" },
  { hanzi:"右边", pinyin:"yòubiān", meaning:"right side", literal:"right + side" },
  { hanzi:"外", pinyin:"wài", meaning:"outside" },
  { hanzi:"旁边", pinyin:"pángbiān", meaning:"next to / side", literal:"side + side" },
  { hanzi:"里面", pinyin:"lǐmiàn", meaning:"inside", literal:"inside + face / side" },
  { hanzi:"早上", pinyin:"zǎoshang", meaning:"morning", literal:"early + up / on" },
  { hanzi:"晚上", pinyin:"wǎnshang", meaning:"evening", literal:"late + up / on" },
  { hanzi:"小时", pinyin:"xiǎoshí", meaning:"hour", literal:"small + time" },
  { hanzi:"时间", pinyin:"shíjiān", meaning:"time", literal:"time + between" },
  { hanzi:"去年", pinyin:"qùnián", meaning:"last year", literal:"go / past + year" },
  { hanzi:"号", pinyin:"hào", meaning:"number / date" },
  { hanzi:"生日", pinyin:"shēngrì", meaning:"birthday", literal:"birth + day" },
  { hanzi:"哥哥", pinyin:"gēge", meaning:"older brother", literal:"older brother (doubled)" },
  { hanzi:"姐姐", pinyin:"jiějie", meaning:"older sister", literal:"older sister (doubled)" },
  { hanzi:"弟弟", pinyin:"dìdi", meaning:"younger brother", literal:"younger brother (doubled)" },
  { hanzi:"妹妹", pinyin:"mèimei", meaning:"younger sister", literal:"younger sister (doubled)" },
  { hanzi:"丈夫", pinyin:"zhàngfu", meaning:"husband", literal:"elder / unit + man" },
  { hanzi:"妻子", pinyin:"qīzi", meaning:"wife", literal:"wife + (noun suffix)" },
  { hanzi:"孩子", pinyin:"háizi", meaning:"child", literal:"child + (noun suffix)" },
  { hanzi:"男人", pinyin:"nánrén", meaning:"man", literal:"male + person" },
  { hanzi:"女人", pinyin:"nǚrén", meaning:"woman", literal:"female + person" },
  { hanzi:"服务员", pinyin:"fúwùyuán", meaning:"waiter / attendant", literal:"serve + affair + member" },
  { hanzi:"鱼", pinyin:"yú", meaning:"fish" },
  { hanzi:"羊肉", pinyin:"yángròu", meaning:"mutton", literal:"sheep + meat" },
  { hanzi:"牛奶", pinyin:"niúnǎi", meaning:"milk", literal:"cow + milk" },
  { hanzi:"鸡蛋", pinyin:"jīdàn", meaning:"egg", literal:"chicken + egg" },
  { hanzi:"西瓜", pinyin:"xīguā", meaning:"watermelon", literal:"west + melon" },
  { hanzi:"咖啡", pinyin:"kāfēi", meaning:"coffee", literal:"phonetic loanword (coffee)" },
  { hanzi:"自行车", pinyin:"zìxíngchē", meaning:"bicycle", literal:"self + go / walk + vehicle" },
  { hanzi:"船", pinyin:"chuán", meaning:"boat" },
  { hanzi:"雪", pinyin:"xuě", meaning:"snow" },
  { hanzi:"药", pinyin:"yào", meaning:"medicine" },
  { hanzi:"手机", pinyin:"shǒujī", meaning:"cell phone", literal:"hand + machine" },
  { hanzi:"手表", pinyin:"shǒubiǎo", meaning:"wristwatch", literal:"hand + watch / gauge" },
  { hanzi:"眼睛", pinyin:"yǎnjīng", meaning:"eye", literal:"eye + eyeball" },
  { hanzi:"身体", pinyin:"shēntǐ", meaning:"body", literal:"body + body" },
  { hanzi:"公共汽车", pinyin:"gōnggòngqìchē", meaning:"bus", literal:"public + together + steam / gas + vehicle" },
  { hanzi:"报纸", pinyin:"bàozhǐ", meaning:"newspaper", literal:"report + paper" },
  { hanzi:"门", pinyin:"mén", meaning:"door" },
  { hanzi:"题", pinyin:"tí", meaning:"question / topic" },
  { hanzi:"课", pinyin:"kè", meaning:"lesson / class" },
  { hanzi:"姓", pinyin:"xìng", meaning:"surname" },
  { hanzi:"问题", pinyin:"wèntí", meaning:"question / problem", literal:"ask + topic" },
  { hanzi:"事情", pinyin:"shìqing", meaning:"matter / affair", literal:"matter + feeling / affair" },
  { hanzi:"考试", pinyin:"kǎoshì", meaning:"exam", literal:"test + try" },
  { hanzi:"票", pinyin:"piào", meaning:"ticket" },
  { hanzi:"意思", pinyin:"yìsi", meaning:"meaning", literal:"idea + think" },
  { hanzi:"颜色", pinyin:"yánsè", meaning:"color", literal:"face / countenance + color" },
  { hanzi:"欢迎", pinyin:"huānyíng", meaning:"welcome", literal:"joyful + greet" },
  { hanzi:"问", pinyin:"wèn", meaning:"to ask" },
  { hanzi:"走", pinyin:"zǒu", meaning:"to walk" },
  { hanzi:"进", pinyin:"jìn", meaning:"to enter" },
  { hanzi:"出", pinyin:"chū", meaning:"to exit" },
  { hanzi:"跑步", pinyin:"pǎobù", meaning:"to run / jog", literal:"run + step" },
  { hanzi:"到", pinyin:"dào", meaning:"to arrive" },
  { hanzi:"穿", pinyin:"chuān", meaning:"to wear" },
  { hanzi:"洗", pinyin:"xǐ", meaning:"to wash" },
  { hanzi:"给", pinyin:"gěi", meaning:"to give" },
  { hanzi:"找", pinyin:"zhǎo", meaning:"to look for" },
  { hanzi:"懂", pinyin:"dǒng", meaning:"to understand" },
  { hanzi:"笑", pinyin:"xiào", meaning:"to laugh / smile" },
  { hanzi:"回答", pinyin:"huídá", meaning:"to answer", literal:"return + answer" },
  { hanzi:"告诉", pinyin:"gàosù", meaning:"to tell", literal:"tell + tell / complain" },
  { hanzi:"准备", pinyin:"zhǔnbèi", meaning:"to prepare", literal:"allow / standard + prepare" },
  { hanzi:"开始", pinyin:"kāishǐ", meaning:"to begin", literal:"open + begin" },
  { hanzi:"介绍", pinyin:"jièshào", meaning:"to introduce", literal:"between + continue / carry on" },
  { hanzi:"帮助", pinyin:"bāngzhù", meaning:"to help", literal:"help + help" },
  { hanzi:"玩", pinyin:"wán", meaning:"to play" },
  { hanzi:"送", pinyin:"sòng", meaning:"to give (a gift) / see off" },
  { hanzi:"等", pinyin:"děng", meaning:"to wait" },
  { hanzi:"让", pinyin:"ràng", meaning:"to let / allow" },
  { hanzi:"起床", pinyin:"qǐchuáng", meaning:"to get up", literal:"rise + bed" },
  { hanzi:"唱歌", pinyin:"chànggē", meaning:"to sing", literal:"sing + song" },
  { hanzi:"跳舞", pinyin:"tiàowǔ", meaning:"to dance", literal:"jump + dance" },
  { hanzi:"旅游", pinyin:"lǚyóu", meaning:"to travel", literal:"travel + roam" },
  { hanzi:"上班", pinyin:"shàngbān", meaning:"to go to work", literal:"up / on + shift / duty" },
  { hanzi:"生病", pinyin:"shēngbìng", meaning:"to fall ill", literal:"produce / develop + sickness" },
  { hanzi:"休息", pinyin:"xiūxi", meaning:"to rest", literal:"rest + breath / rest" },
  { hanzi:"运动", pinyin:"yùndòng", meaning:"to exercise", literal:"move / carry + move" },
  { hanzi:"游泳", pinyin:"yóuyǒng", meaning:"to swim", literal:"swim + swim" },
  { hanzi:"踢足球", pinyin:"tī zúqiú", meaning:"to play soccer", literal:"kick + foot + ball" },
  { hanzi:"打篮球", pinyin:"dǎ lánqiú", meaning:"to play basketball", literal:"hit / play + basket + ball" },
  { hanzi:"完", pinyin:"wán", meaning:"to finish" },
  { hanzi:"觉得", pinyin:"juéde", meaning:"to feel / think", literal:"feel + get / obtain" },
  { hanzi:"知道", pinyin:"zhīdào", meaning:"to know", literal:"know + way / path" },
  { hanzi:"希望", pinyin:"xīwàng", meaning:"to hope", literal:"hope + look towards / hope" },
  { hanzi:"可以", pinyin:"kěyǐ", meaning:"can / may", literal:"can + by means of" },
  { hanzi:"要", pinyin:"yào", meaning:"to want / need" },
  { hanzi:"可能", pinyin:"kěnéng", meaning:"maybe / possibly", literal:"can + able" },
  { hanzi:"高", pinyin:"gāo", meaning:"tall" },
  { hanzi:"红", pinyin:"hóng", meaning:"red" },
  { hanzi:"白", pinyin:"bái", meaning:"white" },
  { hanzi:"黑", pinyin:"hēi", meaning:"black" },
  { hanzi:"忙", pinyin:"máng", meaning:"busy" },
  { hanzi:"快", pinyin:"kuài", meaning:"fast" },
  { hanzi:"慢", pinyin:"màn", meaning:"slow" },
  { hanzi:"远", pinyin:"yuǎn", meaning:"far" },
  { hanzi:"近", pinyin:"jìn", meaning:"close / near" },
  { hanzi:"好吃", pinyin:"hǎochī", meaning:"delicious", literal:"good + eat" },
  { hanzi:"累", pinyin:"lèi", meaning:"tired" },
  { hanzi:"长", pinyin:"cháng", meaning:"long" },
  { hanzi:"新", pinyin:"xīn", meaning:"new" },
  { hanzi:"贵", pinyin:"guì", meaning:"expensive" },
  { hanzi:"便宜", pinyin:"piányi", meaning:"cheap", literal:"convenient + suitable" },
  { hanzi:"晴", pinyin:"qíng", meaning:"clear / sunny" },
  { hanzi:"阴", pinyin:"yīn", meaning:"cloudy / overcast" },
  { hanzi:"错", pinyin:"cuò", meaning:"wrong" },
  { hanzi:"快乐", pinyin:"kuàilè", meaning:"happy", literal:"fast / pleased + happy / music" },
];

// Combined dictionary for pinyin autocomplete, deduped by hanzi.
export const DICTIONARY = (function(){
  const seen = new Set();
  const combined = [];
  [...SEED, ...IMPORT_BATCH_1, ...EXTRA_DICT, ...EXTRA_DICT2].forEach(entry => {
    if(!seen.has(entry.hanzi)){ seen.add(entry.hanzi); combined.push(entry); }
  });
  return combined;
})();

export const CHAR_MEANINGS = {
  "你":"you", "好":"good", "谢":"thank", "朋":"friend", "友":"friend",
  "学":"study", "习":"practice", "时":"time", "间":"between", "明":"bright",
  "天":"sky / day", "喜":"happy", "欢":"joyful", "工":"work", "作":"do / make",
  "我":"I / me", "他":"he", "她":"she", "它":"it", "的":"'s (possessive)",
  "个":"(counter)", "人":"person", "是":"to be", "不":"not", "爱":"love",
  "一":"one", "早":"early", "晚":"late", "安":"peace", "在":"at / located",
  "了":"(completed)", "们":"(plural)", "有":"have", "大":"big", "之":"'s (formal)",
  "这":"this", "为":"for", "日":"sun / day", "太":"too / very", "阳":"sun",
  "月":"moon / month", "那":"that", "谁":"who", "室":"room", "老":"old",
  "师":"teacher / master", "男":"male", "女":"female", "名":"name", "字":"character / word",
  "叫":"call", "什":"what", "么":"(particle)", "请":"please", "问":"ask",
  "对":"correct / facing", "起":"rise", "没":"not have", "关":"close / relate",
  "系":"relate / system", "同":"same", "客":"guest", "气":"air / spirit",
  "快":"fast / happy", "乐":"happy / music", "米":"rice", "饭":"cooked rice / meal",
  "火":"fire", "水":"water", "篮":"basket", "球":"ball", "龙":"dragon",
  "恐":"fear", "亮":"bright", "生":"life / student", "高":"tall / high",
  "兴":"excited", "很":"very", "会":"can / meeting", "说":"speak", "家":"home",
  "口":"mouth", "和":"and", "年":"year", "妈":"mother", "爸":"father",
  "儿":"son / child", "子":"child (suffix)", "猫":"cat", "狗":"dog",
  "书":"book", "笔":"pen", "桌":"table", "椅":"chair", "车":"vehicle",
  "飞":"fly", "机":"machine", "自":"self", "行":"go / walk / okay",
  "校":"school", "医":"medicine / doctor", "院":"institution / yard",
  "商":"commerce", "店":"shop", "公":"public", "司":"manage / company",
  "电":"electric", "话":"words / speech", "脑":"brain", "视":"look / vision",
  "手":"hand", "衣":"clothes", "服":"clothes / serve", "鞋":"shoe", "钱":"money",
  "今":"now / present", "昨":"yesterday", "现":"now / present", "星":"star",
  "期":"period", "上":"up / on", "中":"middle", "午":"noon", "吃":"eat",
  "喝":"drink", "睡":"sleep", "觉":"sleep / sense", "看":"look", "听":"listen",
  "走":"walk", "跑":"run", "跳":"jump", "笑":"laugh", "哭":"cry",
  "矮":"short (height)", "胖":"fat", "瘦":"thin", "漂":"float / pretty",
  "帅":"handsome", "新":"new", "旧":"old (object)", "多":"many", "少":"few",
  "冷":"cold", "热":"hot", "下":"down / under", "雨":"rain", "颜":"color / face",
  "色":"color", "红":"red", "黑":"black", "白":"white", "蓝":"blue",
  "绿":"green", "黄":"yellow", "二":"two", "三":"three", "四":"four",
  "五":"five", "六":"six", "七":"seven", "八":"eight", "九":"nine",
  "十":"ten", "零":"zero", "百":"hundred", "千":"thousand", "万":"ten-thousand",
  "左":"left", "右":"right", "前":"front", "后":"back", "里":"inside",
  "外":"outside", "东":"east", "西":"west", "南":"south", "北":"north",
  "国":"country", "城":"city", "市":"city / market", "头":"head", "眼":"eye",
  "睛":"eyeball", "耳":"ear", "朵":"(counter for ears/flowers)", "鼻":"nose",
  "嘴":"mouth", "脚":"foot", "心":"heart", "去":"go", "来":"come",
  "写":"write", "读":"read", "买":"buy", "卖":"sell", "给":"give",
  "做":"do / make", "坐":"sit", "站":"stand / station", "开":"open",
  "穿":"wear", "用":"use", "玩":"play", "唱":"sing", "歌":"song",
  "舞":"dance", "休":"rest", "息":"rest / breath", "帮":"help", "助":"help",
  "长":"long", "短":"short (length)", "慢":"slow", "贵":"expensive",
  "便":"convenient / cheap", "宜":"suitable / cheap", "干":"dry / do",
  "净":"clean", "脏":"dirty", "容":"contain / allow", "易":"easy / change",
  "难":"difficult", "忙":"busy", "累":"tired", "饿":"hungry", "渴":"thirsty",
  "怎":"how", "哪":"which", "几":"how many", "房":"house / room", "门":"door",
  "窗":"window", "户":"household / door", "床":"bed", "菜":"vegetable / dish",
  "茶":"tea", "咖":"(coffee)", "啡":"(coffee)", "牛":"cow / ox", "奶":"milk",
  "面":"flour / noodle / face", "包":"wrap / bag", "苹":"(apple)", "果":"fruit / result",
  "香":"fragrant", "蕉":"(banana)", "瓜":"melon", "样":"kind / appearance",
  "岁":"years old (age)", "本":"root / (book counter)", "些":"some",
  "块":"piece / lump", "都":"all / both", "吗":"(question)", "呢":"(question)",
  "喂":"hey / hello", "京":"capital", "点":"dot / o'clock", "分":"divide / minute",
  "钟":"clock / bell", "候":"wait / time", "先":"first", "小":"small",
  "姐":"older sister / miss", "杯":"cup", "出":"exit / go out", "租":"rent",
  "影":"shadow / movie", "汉":"Han (Chinese)", "语":"language", "再":"again",
  "见":"see", "回":"return", "打":"hit / do", "住":"live / reside",
  "想":"think / want", "认":"recognize", "识":"know / knowledge", "能":"can / able"
};

export function literalBreakdown(hanzi){
  if(!hanzi || hanzi.length < 2) return null;
  const parts = [];
  for(const ch of hanzi){
    const gloss = CHAR_MEANINGS[ch];
    if(!gloss) return null;
    parts.push(gloss);
  }
  return parts.join(' + ');
}

export function toneless(str){
  return (str || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[0-9]/g, '').toLowerCase();
}
export function tonelessCompact(str){
  return toneless(str).replace(/[\s\-']/g, '');
}

export const Store = {
  async get(key){
    if(typeof window !== 'undefined' && window.storage){
      try{ return await window.storage.get(key, false); }catch(err){ return null; }
    }
    try{
      const raw = localStorage.getItem('hanzi_' + key);
      return raw === null ? null : { key, value: raw, shared: false };
    }catch(err){ return null; }
  },
  async set(key, value){
    if(typeof window !== 'undefined' && window.storage){
      try{ return await window.storage.set(key, value, false); }catch(err){ return null; }
    }
    try{ localStorage.setItem('hanzi_' + key, value); return { key, value, shared: false }; }catch(err){ return null; }
  }
};

export function uid(){ return 'c' + Date.now().toString(36) + Math.random().toString(36).slice(2,7); }

export function newCard(hanzi, pinyin, meaning, deck, literal){
  return { id: uid(), hanzi, pinyin, meaning, deck: (deck || 'General'), literal: (literal || '').trim(), suspended: false, learned: false, learnedAt: null, ease: 2.5, interval: 0, reps: 0, due: Date.now(), created: Date.now() };
}

export const DAY = 86400000;
const MINUTE = 60000;

export function schedule(card, rating){
  const now = Date.now();
  if(rating === 'again'){ card.reps = 0; card.interval = 0; card.due = now + 2 * MINUTE; }
  else if(rating === 'hard'){ card.interval = 10 * MINUTE / DAY; card.due = now + 10 * MINUTE; card.reps += 1; }
  else if(rating === 'good'){ card.interval = 1; card.due = now + 1 * DAY; card.reps += 1; }
  else if(rating === 'easy'){ card.interval = 3; card.due = now + 3 * DAY; card.reps += 1; }
}

export function previewInterval(card, rating){
  const clone = JSON.parse(JSON.stringify(card));
  schedule(clone, rating);
  const ms = clone.due - Date.now();
  const mins = Math.round(ms / MINUTE);
  if(mins < 60) return mins + ' min';
  const hours = Math.round(mins / 60);
  if(hours < 24) return hours + ' hr';
  const days = Math.round(hours / 24);
  if(days === 1) return '1 day';
  if(days < 30) return days + ' days';
  if(days < 365) return Math.round(days/30) + ' mo';
  return Math.round(days/365) + ' yr';
}

export function dueIn(ms){
  const days = Math.round(ms / DAY);
  if(days <= 0) return 'due now';
  if(days === 1) return 'in 1 day';
  if(days < 30) return 'in ' + days + ' days';
  return 'in ' + Math.round(days/30) + ' mo';
}

export async function runImportBatch(cards, batch, flagKey, deck){
  try{
    const flag = await Store.get(flagKey);
    if(flag && flag.value === "true") return 0;
  }catch(err){ /* proceed */ }
  const existingHanzi = new Set(cards.map(c => c.hanzi));
  let added = 0;
  batch.forEach(item => {
    if(!existingHanzi.has(item.hanzi)){
      cards.push(newCard(item.hanzi, item.pinyin, item.meaning, deck || 'General', item.literal));
      existingHanzi.add(item.hanzi);
      added++;
    }
  });
  await Store.set(flagKey, "true");
  return added;
}
