// Shared business logic + vocab data for the Hanzi Cards flashcard app.
// Plain ES module — no npm imports, no DOM access at module scope.

export const SEED = [
  { hanzi:"你好", pinyin:"nǐ hǎo", meaning:"hello" },
  { hanzi:"谢谢", pinyin:"xiè xiè", meaning:"thank you" },
  { hanzi:"朋友", pinyin:"péng yǒu", meaning:"friend" },
  { hanzi:"学习", pinyin:"xué xí", meaning:"to study" },
  { hanzi:"时间", pinyin:"shí jiān", meaning:"time" },
  { hanzi:"明天", pinyin:"míng tiān", meaning:"tomorrow" },
  { hanzi:"喜欢", pinyin:"xǐ huān", meaning:"to like" },
  { hanzi:"工作", pinyin:"gōng zuò", meaning:"work / job" },
];

export const IMPORT_BATCH_1 = [
  { hanzi:"我", pinyin:"wǒ", meaning:"I / me" },
  { hanzi:"你", pinyin:"nǐ", meaning:"you" },
  { hanzi:"他", pinyin:"tā", meaning:"he / him" },
  { hanzi:"她", pinyin:"tā", meaning:"she / her" },
  { hanzi:"它", pinyin:"tā", meaning:"it" },
  { hanzi:"的", pinyin:"de", meaning:"possessive particle ('s)" },
  { hanzi:"个", pinyin:"gè", meaning:"measure word (general)" },
  { hanzi:"人", pinyin:"rén", meaning:"person" },
  { hanzi:"是", pinyin:"shì", meaning:"to be" },
  { hanzi:"不", pinyin:"bù", meaning:"not / no" },
  { hanzi:"爱", pinyin:"ài", meaning:"love" },
  { hanzi:"一", pinyin:"yī", meaning:"one" },
  { hanzi:"早", pinyin:"zǎo", meaning:"early / morning" },
  { hanzi:"晚", pinyin:"wǎn", meaning:"late / evening" },
  { hanzi:"安", pinyin:"ān", meaning:"peace / safe" },
  { hanzi:"早安", pinyin:"zǎo ān", meaning:"good morning" },
  { hanzi:"晚安", pinyin:"wǎn ān", meaning:"good night" },
  { hanzi:"在", pinyin:"zài", meaning:"at / in / located" },
  { hanzi:"了", pinyin:"le", meaning:"completed-action particle" },
  { hanzi:"们", pinyin:"men", meaning:"plural marker (we/they)" },
  { hanzi:"有", pinyin:"yǒu", meaning:"to have" },
  { hanzi:"大", pinyin:"dà", meaning:"big" },
  { hanzi:"之", pinyin:"zhī", meaning:"possessive particle (formal)" },
  { hanzi:"这", pinyin:"zhè", meaning:"this" },
  { hanzi:"为", pinyin:"weì", meaning:"for / because of" },
  { hanzi:"日", pinyin:"rì", meaning:"day / sun" },
  { hanzi:"好", pinyin:"hǎo", meaning:"good" },
  { hanzi:"太阳", pinyin:"tài-yáng", meaning:"sun" },
  { hanzi:"月", pinyin:"yuè", meaning:"moon / month" },
  { hanzi:"那", pinyin:"nà", meaning:"that" },
  { hanzi:"谁", pinyin:"shéi", meaning:"who" },
  { hanzi:"室友", pinyin:"shì-yǒu", meaning:"roommate" },
  { hanzi:"老师", pinyin:"lǎo-shī", meaning:"teacher" },
  { hanzi:"男朋友", pinyin:"nán péng-yǒu", meaning:"boyfriend" },
  { hanzi:"女朋友", pinyin:"nü péng-yǒu", meaning:"girlfriend" },
  { hanzi:"名字", pinyin:"míng-zì", meaning:"name" },
  { hanzi:"叫", pinyin:"jiào", meaning:"to be called" },
  { hanzi:"是的", pinyin:"shì de", meaning:"yes / that's right" },
  { hanzi:"什么", pinyin:"shí-me", meaning:"what" },
  { hanzi:"请", pinyin:"qǐng", meaning:"please" },
  { hanzi:"问", pinyin:"wèn", meaning:"to ask" },
  { hanzi:"请问", pinyin:"qǐng wèn", meaning:"excuse me / may I ask" },
  { hanzi:"对不起", pinyin:"duì-bù-qì", meaning:"sorry" },
  { hanzi:"没关系", pinyin:"méi-guān-xì", meaning:"it's okay / no problem" },
  { hanzi:"同学", pinyin:"tóng-xué", meaning:"classmate" },
  { hanzi:"不客气", pinyin:"bù kè qì", meaning:"you're welcome" },
  { hanzi:"谢谢", pinyin:"xiè-xiè", meaning:"thank you" },
  { hanzi:"快乐", pinyin:"kuài-lè", meaning:"happy" },
  { hanzi:"米饭", pinyin:"mǐ fàn", meaning:"cooked rice" },
  { hanzi:"好的", pinyin:"hǎo de", meaning:"okay / sounds good" },
  { hanzi:"火", pinyin:"huo", meaning:"fire" },
  { hanzi:"水", pinyin:"shuǐ", meaning:"water" },
  { hanzi:"篮球", pinyin:"lán-qiú", meaning:"basketball" },
  { hanzi:"龙", pinyin:"lóng", meaning:"dragon" },
  { hanzi:"恐龙", pinyin:"kǒng-lóng", meaning:"dinosaur" },
  { hanzi:"月亮", pinyin:"yuè-liàng", meaning:"moon" },
  { hanzi:"学生", pinyin:"xué-shēng", meaning:"student" },
  { hanzi:"高兴", pinyin:"gão-shìng", meaning:"happy / glad" },
  { hanzi:"很", pinyin:"hěn", meaning:"very" },
  { hanzi:"会说", pinyin:"huì shuō", meaning:"can speak" },
  { hanzi:"对", pinyin:"duì", meaning:"correct / right" },
  { hanzi:"家", pinyin:"jiā", meaning:"home / family" },
  { hanzi:"口人", pinyin:"kǒu rén", meaning:"members of the family (measure)" },
  { hanzi:"和", pinyin:"hé", meaning:"and" },
  { hanzi:"年", pinyin:"nián", meaning:"year" },
];

export const EXTRA_DICT = [
  { hanzi:"妈妈", pinyin:"māma", meaning:"mom" },
  { hanzi:"爸爸", pinyin:"bàba", meaning:"dad" },
  { hanzi:"儿子", pinyin:"érzi", meaning:"son" },
  { hanzi:"女儿", pinyin:"nǚ'ér", meaning:"daughter" },
  { hanzi:"猫", pinyin:"māo", meaning:"cat" },
  { hanzi:"狗", pinyin:"gǒu", meaning:"dog" },
  { hanzi:"书", pinyin:"shū", meaning:"book" },
  { hanzi:"笔", pinyin:"bǐ", meaning:"pen" },
  { hanzi:"桌子", pinyin:"zhuōzi", meaning:"table" },
  { hanzi:"椅子", pinyin:"yǐzi", meaning:"chair" },
  { hanzi:"车", pinyin:"chē", meaning:"car" },
  { hanzi:"飞机", pinyin:"fēijī", meaning:"airplane" },
  { hanzi:"火车", pinyin:"huǒchē", meaning:"train" },
  { hanzi:"自行车", pinyin:"zìxíngchē", meaning:"bicycle" },
  { hanzi:"学校", pinyin:"xuéxiào", meaning:"school" },
  { hanzi:"医院", pinyin:"yīyuàn", meaning:"hospital" },
  { hanzi:"商店", pinyin:"shāngdiàn", meaning:"store" },
  { hanzi:"公司", pinyin:"gōngsī", meaning:"company" },
  { hanzi:"电话", pinyin:"diànhuà", meaning:"phone" },
  { hanzi:"电脑", pinyin:"diànnǎo", meaning:"computer" },
  { hanzi:"电视", pinyin:"diànshì", meaning:"television" },
  { hanzi:"手机", pinyin:"shǒujī", meaning:"cell phone" },
  { hanzi:"衣服", pinyin:"yīfu", meaning:"clothes" },
  { hanzi:"鞋", pinyin:"xié", meaning:"shoes" },
  { hanzi:"钱", pinyin:"qián", meaning:"money" },
  { hanzi:"今天", pinyin:"jīntiān", meaning:"today" },
  { hanzi:"昨天", pinyin:"zuótiān", meaning:"yesterday" },
  { hanzi:"明天", pinyin:"míngtiān", meaning:"tomorrow" },
  { hanzi:"现在", pinyin:"xiànzài", meaning:"now" },
  { hanzi:"星期", pinyin:"xīngqī", meaning:"week" },
  { hanzi:"早上", pinyin:"zǎoshang", meaning:"morning" },
  { hanzi:"晚上", pinyin:"wǎnshang", meaning:"evening" },
  { hanzi:"中午", pinyin:"zhōngwǔ", meaning:"noon" },
  { hanzi:"吃", pinyin:"chī", meaning:"to eat" },
  { hanzi:"喝", pinyin:"hē", meaning:"to drink" },
  { hanzi:"睡觉", pinyin:"shuìjiào", meaning:"to sleep" },
  { hanzi:"看", pinyin:"kàn", meaning:"to look / watch" },
  { hanzi:"听", pinyin:"tīng", meaning:"to listen" },
  { hanzi:"走", pinyin:"zǒu", meaning:"to walk" },
  { hanzi:"跑", pinyin:"pǎo", meaning:"to run" },
  { hanzi:"跳", pinyin:"tiào", meaning:"to jump" },
  { hanzi:"笑", pinyin:"xiào", meaning:"to laugh" },
  { hanzi:"哭", pinyin:"kū", meaning:"to cry" },
  { hanzi:"高", pinyin:"gāo", meaning:"tall" },
  { hanzi:"矮", pinyin:"ǎi", meaning:"short (height)" },
  { hanzi:"胖", pinyin:"pàng", meaning:"fat" },
  { hanzi:"瘦", pinyin:"shòu", meaning:"thin" },
  { hanzi:"漂亮", pinyin:"piàoliang", meaning:"pretty" },
  { hanzi:"帅", pinyin:"shuài", meaning:"handsome" },
  { hanzi:"新", pinyin:"xīn", meaning:"new" },
  { hanzi:"旧", pinyin:"jiù", meaning:"old (object)" },
  { hanzi:"多", pinyin:"duō", meaning:"many / much" },
  { hanzi:"少", pinyin:"shǎo", meaning:"few / little" },
  { hanzi:"冷", pinyin:"lěng", meaning:"cold" },
  { hanzi:"热", pinyin:"rè", meaning:"hot" },
  { hanzi:"天气", pinyin:"tiānqì", meaning:"weather" },
  { hanzi:"下雨", pinyin:"xiàyǔ", meaning:"to rain" },
  { hanzi:"颜色", pinyin:"yánsè", meaning:"color" },
  { hanzi:"红色", pinyin:"hóngsè", meaning:"red" },
  { hanzi:"黑色", pinyin:"hēisè", meaning:"black" },
  { hanzi:"白色", pinyin:"báisè", meaning:"white" },
  { hanzi:"蓝色", pinyin:"lánsè", meaning:"blue" },
  { hanzi:"绿色", pinyin:"lǜsè", meaning:"green" },
  { hanzi:"黄色", pinyin:"huángsè", meaning:"yellow" },
];

export const EXTRA_DICT2 = [
  { hanzi:"二", pinyin:"èr", meaning:"two" },
  { hanzi:"三", pinyin:"sān", meaning:"three" },
  { hanzi:"四", pinyin:"sì", meaning:"four" },
  { hanzi:"五", pinyin:"wǔ", meaning:"five" },
  { hanzi:"六", pinyin:"liù", meaning:"six" },
  { hanzi:"七", pinyin:"qī", meaning:"seven" },
  { hanzi:"八", pinyin:"bā", meaning:"eight" },
  { hanzi:"九", pinyin:"jiǔ", meaning:"nine" },
  { hanzi:"十", pinyin:"shí", meaning:"ten" },
  { hanzi:"零", pinyin:"líng", meaning:"zero" },
  { hanzi:"百", pinyin:"bǎi", meaning:"hundred" },
  { hanzi:"千", pinyin:"qiān", meaning:"thousand" },
  { hanzi:"万", pinyin:"wàn", meaning:"ten thousand" },
  { hanzi:"星期一", pinyin:"xīngqīyī", meaning:"Monday" },
  { hanzi:"星期二", pinyin:"xīngqīèr", meaning:"Tuesday" },
  { hanzi:"星期三", pinyin:"xīngqīsān", meaning:"Wednesday" },
  { hanzi:"星期四", pinyin:"xīngqīsì", meaning:"Thursday" },
  { hanzi:"星期五", pinyin:"xīngqīwǔ", meaning:"Friday" },
  { hanzi:"星期六", pinyin:"xīngqīliù", meaning:"Saturday" },
  { hanzi:"星期天", pinyin:"xīngqītiān", meaning:"Sunday" },
  { hanzi:"上", pinyin:"shàng", meaning:"up / on" },
  { hanzi:"下", pinyin:"xià", meaning:"down / under" },
  { hanzi:"左", pinyin:"zuǒ", meaning:"left" },
  { hanzi:"右", pinyin:"yòu", meaning:"right" },
  { hanzi:"前", pinyin:"qián", meaning:"front / before" },
  { hanzi:"后", pinyin:"hòu", meaning:"back / after" },
  { hanzi:"里", pinyin:"lǐ", meaning:"inside" },
  { hanzi:"外", pinyin:"wài", meaning:"outside" },
  { hanzi:"东", pinyin:"dōng", meaning:"east" },
  { hanzi:"西", pinyin:"xī", meaning:"west" },
  { hanzi:"南", pinyin:"nán", meaning:"south" },
  { hanzi:"北", pinyin:"běi", meaning:"north" },
  { hanzi:"中国", pinyin:"zhōngguó", meaning:"China" },
  { hanzi:"国家", pinyin:"guójiā", meaning:"country" },
  { hanzi:"城市", pinyin:"chéngshì", meaning:"city" },
  { hanzi:"头", pinyin:"tóu", meaning:"head" },
  { hanzi:"眼睛", pinyin:"yǎnjīng", meaning:"eyes" },
  { hanzi:"耳朵", pinyin:"ěrduo", meaning:"ears" },
  { hanzi:"鼻子", pinyin:"bízi", meaning:"nose" },
  { hanzi:"嘴", pinyin:"zuǐ", meaning:"mouth" },
  { hanzi:"手", pinyin:"shǒu", meaning:"hand" },
  { hanzi:"脚", pinyin:"jiǎo", meaning:"foot" },
  { hanzi:"心", pinyin:"xīn", meaning:"heart" },
  { hanzi:"去", pinyin:"qù", meaning:"to go" },
  { hanzi:"来", pinyin:"lái", meaning:"to come" },
  { hanzi:"说", pinyin:"shuō", meaning:"to speak" },
  { hanzi:"写", pinyin:"xiě", meaning:"to write" },
  { hanzi:"读", pinyin:"dú", meaning:"to read" },
  { hanzi:"买", pinyin:"mǎi", meaning:"to buy" },
  { hanzi:"卖", pinyin:"mài", meaning:"to sell" },
  { hanzi:"给", pinyin:"gěi", meaning:"to give" },
  { hanzi:"做", pinyin:"zuò", meaning:"to do / make" },
  { hanzi:"坐", pinyin:"zuò", meaning:"to sit" },
  { hanzi:"站", pinyin:"zhàn", meaning:"to stand" },
  { hanzi:"开", pinyin:"kāi", meaning:"to open" },
  { hanzi:"关", pinyin:"guān", meaning:"to close" },
  { hanzi:"穿", pinyin:"chuān", meaning:"to wear" },
  { hanzi:"用", pinyin:"yòng", meaning:"to use" },
  { hanzi:"玩", pinyin:"wán", meaning:"to play" },
  { hanzi:"唱歌", pinyin:"chànggē", meaning:"to sing" },
  { hanzi:"跳舞", pinyin:"tiàowǔ", meaning:"to dance" },
  { hanzi:"休息", pinyin:"xiūxi", meaning:"to rest" },
  { hanzi:"帮助", pinyin:"bāngzhù", meaning:"to help" },
  { hanzi:"长", pinyin:"cháng", meaning:"long" },
  { hanzi:"短", pinyin:"duǎn", meaning:"short (length)" },
  { hanzi:"快", pinyin:"kuài", meaning:"fast" },
  { hanzi:"慢", pinyin:"màn", meaning:"slow" },
  { hanzi:"贵", pinyin:"guì", meaning:"expensive" },
  { hanzi:"便宜", pinyin:"piányi", meaning:"cheap" },
  { hanzi:"干净", pinyin:"gānjìng", meaning:"clean" },
  { hanzi:"脏", pinyin:"zāng", meaning:"dirty" },
  { hanzi:"容易", pinyin:"róngyì", meaning:"easy" },
  { hanzi:"难", pinyin:"nán", meaning:"difficult" },
  { hanzi:"忙", pinyin:"máng", meaning:"busy" },
  { hanzi:"累", pinyin:"lèi", meaning:"tired" },
  { hanzi:"饿", pinyin:"è", meaning:"hungry" },
  { hanzi:"渴", pinyin:"kě", meaning:"thirsty" },
  { hanzi:"怎么", pinyin:"zěnme", meaning:"how" },
  { hanzi:"为什么", pinyin:"wèishénme", meaning:"why" },
  { hanzi:"哪", pinyin:"nǎ", meaning:"which" },
  { hanzi:"哪里", pinyin:"nǎlǐ", meaning:"where" },
  { hanzi:"多少", pinyin:"duōshǎo", meaning:"how many / much" },
  { hanzi:"几", pinyin:"jǐ", meaning:"how many (small numbers)" },
  { hanzi:"房子", pinyin:"fángzi", meaning:"house" },
  { hanzi:"房间", pinyin:"fángjiān", meaning:"room" },
  { hanzi:"门", pinyin:"mén", meaning:"door" },
  { hanzi:"窗户", pinyin:"chuānghu", meaning:"window" },
  { hanzi:"床", pinyin:"chuáng", meaning:"bed" },
  { hanzi:"饭", pinyin:"fàn", meaning:"meal / rice" },
  { hanzi:"菜", pinyin:"cài", meaning:"dish / vegetable" },
  { hanzi:"茶", pinyin:"chá", meaning:"tea" },
  { hanzi:"咖啡", pinyin:"kāfēi", meaning:"coffee" },
  { hanzi:"牛奶", pinyin:"niúnǎi", meaning:"milk" },
  { hanzi:"面包", pinyin:"miànbāo", meaning:"bread" },
  { hanzi:"苹果", pinyin:"píngguǒ", meaning:"apple" },
  { hanzi:"香蕉", pinyin:"xiāngjiāo", meaning:"banana" },
  { hanzi:"西瓜", pinyin:"xīguā", meaning:"watermelon" },
];

export const IMPORT_BATCH_HSK1 = [
  { hanzi:"我", pinyin:"wǒ", meaning:"I / me" },
  { hanzi:"我们", pinyin:"wǒmen", meaning:"we / us" },
  { hanzi:"你", pinyin:"nǐ", meaning:"you" },
  { hanzi:"你们", pinyin:"nǐmen", meaning:"you (plural)" },
  { hanzi:"他", pinyin:"tā", meaning:"he / him" },
  { hanzi:"她", pinyin:"tā", meaning:"she / her" },
  { hanzi:"他们", pinyin:"tāmen", meaning:"they (mixed / male)" },
  { hanzi:"她们", pinyin:"tāmen", meaning:"they (female)" },
  { hanzi:"这", pinyin:"zhè", meaning:"this" },
  { hanzi:"那", pinyin:"nà", meaning:"that" },
  { hanzi:"哪", pinyin:"nǎ", meaning:"which / where" },
  { hanzi:"谁", pinyin:"shéi", meaning:"who" },
  { hanzi:"什么", pinyin:"shénme", meaning:"what" },
  { hanzi:"多少", pinyin:"duōshǎo", meaning:"how many / how much" },
  { hanzi:"几", pinyin:"jǐ", meaning:"how many (small numbers)" },
  { hanzi:"怎么", pinyin:"zěnme", meaning:"how" },
  { hanzi:"怎么样", pinyin:"zěnmeyàng", meaning:"how is it / how about" },
  { hanzi:"一", pinyin:"yī", meaning:"one" },
  { hanzi:"二", pinyin:"èr", meaning:"two" },
  { hanzi:"三", pinyin:"sān", meaning:"three" },
  { hanzi:"四", pinyin:"sì", meaning:"four" },
  { hanzi:"五", pinyin:"wǔ", meaning:"five" },
  { hanzi:"六", pinyin:"liù", meaning:"six" },
  { hanzi:"七", pinyin:"qī", meaning:"seven" },
  { hanzi:"八", pinyin:"bā", meaning:"eight" },
  { hanzi:"九", pinyin:"jiǔ", meaning:"nine" },
  { hanzi:"十", pinyin:"shí", meaning:"ten" },
  { hanzi:"零", pinyin:"líng", meaning:"zero" },
  { hanzi:"个", pinyin:"gè", meaning:"measure word (general)" },
  { hanzi:"岁", pinyin:"suì", meaning:"years old (age)" },
  { hanzi:"本", pinyin:"běn", meaning:"measure word for books" },
  { hanzi:"些", pinyin:"xiē", meaning:"some / a few" },
  { hanzi:"块", pinyin:"kuài", meaning:"piece / dollar (money)" },
  { hanzi:"不", pinyin:"bù", meaning:"not / no" },
  { hanzi:"没", pinyin:"méi", meaning:"not / haven't" },
  { hanzi:"很", pinyin:"hěn", meaning:"very" },
  { hanzi:"太", pinyin:"tài", meaning:"too (excessively)" },
  { hanzi:"都", pinyin:"dōu", meaning:"all / both" },
  { hanzi:"和", pinyin:"hé", meaning:"and" },
  { hanzi:"在", pinyin:"zài", meaning:"at / in" },
  { hanzi:"的", pinyin:"de", meaning:"possessive particle" },
  { hanzi:"了", pinyin:"le", meaning:"completed-action particle" },
  { hanzi:"吗", pinyin:"ma", meaning:"question particle" },
  { hanzi:"呢", pinyin:"ne", meaning:"question particle" },
  { hanzi:"喂", pinyin:"wèi", meaning:"hello (on the phone)" },
  { hanzi:"家", pinyin:"jiā", meaning:"home / family" },
  { hanzi:"学校", pinyin:"xuéxiào", meaning:"school" },
  { hanzi:"饭店", pinyin:"fàndiàn", meaning:"restaurant" },
  { hanzi:"商店", pinyin:"shāngdiàn", meaning:"store" },
  { hanzi:"医院", pinyin:"yīyuàn", meaning:"hospital" },
  { hanzi:"火车站", pinyin:"huǒchēzhàn", meaning:"train station" },
  { hanzi:"中国", pinyin:"zhōngguó", meaning:"China" },
  { hanzi:"北京", pinyin:"běijīng", meaning:"Beijing" },
  { hanzi:"上", pinyin:"shàng", meaning:"up / on" },
  { hanzi:"下", pinyin:"xià", meaning:"down / under" },
  { hanzi:"前面", pinyin:"qiánmiàn", meaning:"front" },
  { hanzi:"后面", pinyin:"hòumiàn", meaning:"behind" },
  { hanzi:"里", pinyin:"lǐ", meaning:"inside" },
  { hanzi:"今天", pinyin:"jīntiān", meaning:"today" },
  { hanzi:"明天", pinyin:"míngtiān", meaning:"tomorrow" },
  { hanzi:"昨天", pinyin:"zuótiān", meaning:"yesterday" },
  { hanzi:"上午", pinyin:"shàngwǔ", meaning:"morning" },
  { hanzi:"中午", pinyin:"zhōngwǔ", meaning:"noon" },
  { hanzi:"下午", pinyin:"xiàwǔ", meaning:"afternoon" },
  { hanzi:"年", pinyin:"nián", meaning:"year" },
  { hanzi:"月", pinyin:"yuè", meaning:"month" },
  { hanzi:"日", pinyin:"rì", meaning:"day" },
  { hanzi:"星期", pinyin:"xīngqī", meaning:"week" },
  { hanzi:"点", pinyin:"diǎn", meaning:"o'clock / dot" },
  { hanzi:"分钟", pinyin:"fēnzhōng", meaning:"minute" },
  { hanzi:"现在", pinyin:"xiànzài", meaning:"now" },
  { hanzi:"时候", pinyin:"shíhou", meaning:"time / moment" },
  { hanzi:"爸爸", pinyin:"bàba", meaning:"father" },
  { hanzi:"妈妈", pinyin:"māma", meaning:"mother" },
  { hanzi:"儿子", pinyin:"érzi", meaning:"son" },
  { hanzi:"女儿", pinyin:"nǚér", meaning:"daughter" },
  { hanzi:"老师", pinyin:"lǎoshī", meaning:"teacher" },
  { hanzi:"学生", pinyin:"xuéshēng", meaning:"student" },
  { hanzi:"同学", pinyin:"tóngxué", meaning:"classmate" },
  { hanzi:"朋友", pinyin:"péngyou", meaning:"friend" },
  { hanzi:"医生", pinyin:"yīshēng", meaning:"doctor" },
  { hanzi:"先生", pinyin:"xiānsheng", meaning:"mister / sir" },
  { hanzi:"小姐", pinyin:"xiǎojiě", meaning:"miss" },
  { hanzi:"衣服", pinyin:"yīfu", meaning:"clothes" },
  { hanzi:"水", pinyin:"shuǐ", meaning:"water" },
  { hanzi:"菜", pinyin:"cài", meaning:"vegetable / dish" },
  { hanzi:"米饭", pinyin:"mǐfàn", meaning:"cooked rice" },
  { hanzi:"水果", pinyin:"shuǐguǒ", meaning:"fruit" },
  { hanzi:"苹果", pinyin:"píngguǒ", meaning:"apple" },
  { hanzi:"茶", pinyin:"chá", meaning:"tea" },
  { hanzi:"杯子", pinyin:"bēizi", meaning:"cup" },
  { hanzi:"钱", pinyin:"qián", meaning:"money" },
  { hanzi:"飞机", pinyin:"fēijī", meaning:"airplane" },
  { hanzi:"出租车", pinyin:"chūzūchē", meaning:"taxi" },
  { hanzi:"电视", pinyin:"diànshì", meaning:"television" },
  { hanzi:"电脑", pinyin:"diànnǎo", meaning:"computer" },
  { hanzi:"电影", pinyin:"diànyǐng", meaning:"movie" },
  { hanzi:"天气", pinyin:"tiānqì", meaning:"weather" },
  { hanzi:"猫", pinyin:"māo", meaning:"cat" },
  { hanzi:"狗", pinyin:"gǒu", meaning:"dog" },
  { hanzi:"东西", pinyin:"dōngxi", meaning:"thing" },
  { hanzi:"人", pinyin:"rén", meaning:"person" },
  { hanzi:"名字", pinyin:"míngzi", meaning:"name" },
  { hanzi:"书", pinyin:"shū", meaning:"book" },
  { hanzi:"汉语", pinyin:"hànyǔ", meaning:"Chinese (language)" },
  { hanzi:"字", pinyin:"zì", meaning:"(written) character" },
  { hanzi:"桌子", pinyin:"zhuōzi", meaning:"desk" },
  { hanzi:"椅子", pinyin:"yǐzi", meaning:"chair" },
  { hanzi:"谢谢", pinyin:"xièxie", meaning:"thank you" },
  { hanzi:"不客气", pinyin:"búkèqì", meaning:"you're welcome" },
  { hanzi:"再见", pinyin:"zàijiàn", meaning:"goodbye" },
  { hanzi:"请", pinyin:"qǐng", meaning:"please" },
  { hanzi:"对不起", pinyin:"duìbùqǐ", meaning:"sorry" },
  { hanzi:"没关系", pinyin:"méiguānxì", meaning:"it doesn't matter" },
  { hanzi:"是", pinyin:"shì", meaning:"to be" },
  { hanzi:"有", pinyin:"yǒu", meaning:"to have" },
  { hanzi:"看", pinyin:"kàn", meaning:"to look / watch" },
  { hanzi:"听", pinyin:"tīng", meaning:"to listen" },
  { hanzi:"说话", pinyin:"shuōhuà", meaning:"to speak / talk" },
  { hanzi:"读", pinyin:"dú", meaning:"to read" },
  { hanzi:"写", pinyin:"xiě", meaning:"to write" },
  { hanzi:"看见", pinyin:"kànjiàn", meaning:"to see" },
  { hanzi:"叫", pinyin:"jiào", meaning:"to be called" },
  { hanzi:"来", pinyin:"lái", meaning:"to come" },
  { hanzi:"回", pinyin:"huí", meaning:"to return" },
  { hanzi:"去", pinyin:"qù", meaning:"to go" },
  { hanzi:"吃", pinyin:"chī", meaning:"to eat" },
  { hanzi:"喝", pinyin:"hē", meaning:"to drink" },
  { hanzi:"睡觉", pinyin:"shuìjiào", meaning:"to sleep" },
  { hanzi:"打电话", pinyin:"dǎ diànhuà", meaning:"to make a phone call" },
  { hanzi:"做", pinyin:"zuò", meaning:"to do" },
  { hanzi:"买", pinyin:"mǎi", meaning:"to buy" },
  { hanzi:"开", pinyin:"kāi", meaning:"to open" },
  { hanzi:"坐", pinyin:"zuò", meaning:"to sit" },
  { hanzi:"住", pinyin:"zhù", meaning:"to live / reside" },
  { hanzi:"学习", pinyin:"xuéxí", meaning:"to study" },
  { hanzi:"工作", pinyin:"gōngzuò", meaning:"to work" },
  { hanzi:"下雨", pinyin:"xiàyǔ", meaning:"to rain" },
  { hanzi:"爱", pinyin:"ài", meaning:"to love" },
  { hanzi:"喜欢", pinyin:"xǐhuan", meaning:"to like" },
  { hanzi:"想", pinyin:"xiǎng", meaning:"to want / to think" },
  { hanzi:"认识", pinyin:"rènshi", meaning:"to know (a person)" },
  { hanzi:"会", pinyin:"huì", meaning:"can / know how to" },
  { hanzi:"能", pinyin:"néng", meaning:"can / to be able to" },
  { hanzi:"好", pinyin:"hǎo", meaning:"good" },
  { hanzi:"大", pinyin:"dà", meaning:"big" },
  { hanzi:"小", pinyin:"xiǎo", meaning:"small" },
  { hanzi:"多", pinyin:"duō", meaning:"many / much" },
  { hanzi:"少", pinyin:"shǎo", meaning:"few / little" },
  { hanzi:"冷", pinyin:"lěng", meaning:"cold" },
  { hanzi:"热", pinyin:"rè", meaning:"hot" },
  { hanzi:"高兴", pinyin:"gāoxìng", meaning:"happy" },
  { hanzi:"漂亮", pinyin:"piàoliang", meaning:"beautiful" },
];

export const IMPORT_BATCH_HSK2 = [
  { hanzi:"您", pinyin:"nín", meaning:"you (polite)" },
  { hanzi:"它", pinyin:"tā", meaning:"it" },
  { hanzi:"大家", pinyin:"dàjiā", meaning:"everyone", literal:"big + family" },
  { hanzi:"每", pinyin:"měi", meaning:"every" },
  { hanzi:"为什么", pinyin:"wèishénme", meaning:"why", literal:"for + what" },
  { hanzi:"两", pinyin:"liǎng", meaning:"two (of something)" },
  { hanzi:"第一", pinyin:"dìyī", meaning:"first", literal:"ordinal marker + one" },
  { hanzi:"次", pinyin:"cì", meaning:"time / occurrence" },
  { hanzi:"公斤", pinyin:"gōngjīn", meaning:"kilogram", literal:"public + catty (unit)" },
  { hanzi:"元", pinyin:"yuán", meaning:"yuan (currency)" },
  { hanzi:"件", pinyin:"jiàn", meaning:"item (measure word)" },
  { hanzi:"张", pinyin:"zhāng", meaning:"sheet (measure word)" },
  { hanzi:"别", pinyin:"bié", meaning:"don't" },
  { hanzi:"非常", pinyin:"fēicháng", meaning:"very / extremely", literal:"not + ordinary" },
  { hanzi:"也", pinyin:"yě", meaning:"also / too" },
  { hanzi:"还", pinyin:"hái", meaning:"still / also" },
  { hanzi:"最", pinyin:"zuì", meaning:"most" },
  { hanzi:"真", pinyin:"zhēn", meaning:"really / truly" },
  { hanzi:"正在", pinyin:"zhèngzài", meaning:"in the middle of (doing)", literal:"just / precisely + at" },
  { hanzi:"已经", pinyin:"yǐjīng", meaning:"already", literal:"already + pass through" },
  { hanzi:"一起", pinyin:"yìqǐ", meaning:"together", literal:"one + rise / together" },
  { hanzi:"再", pinyin:"zài", meaning:"again" },
  { hanzi:"就", pinyin:"jiù", meaning:"then / right away" },
  { hanzi:"因为", pinyin:"yīnwèi", meaning:"because", literal:"reason + for" },
  { hanzi:"所以", pinyin:"suǒyǐ", meaning:"so / therefore", literal:"that which + by means of" },
  { hanzi:"但是", pinyin:"dànshì", meaning:"but", literal:"but + is" },
  { hanzi:"从", pinyin:"cóng", meaning:"from" },
  { hanzi:"此", pinyin:"cǐ", meaning:"this (formal)" },
  { hanzi:"向", pinyin:"xiàng", meaning:"towards" },
  { hanzi:"离", pinyin:"lí", meaning:"away from / distance to" },
  { hanzi:"得", pinyin:"de", meaning:"complement particle" },
  { hanzi:"着", pinyin:"zhe", meaning:"continuous-action particle" },
  { hanzi:"过", pinyin:"guo", meaning:"experiential-action particle" },
  { hanzi:"吧", pinyin:"ba", meaning:"suggestion particle" },
  { hanzi:"饭馆", pinyin:"fànguǎn", meaning:"restaurant", literal:"meal + establishment / hall" },
  { hanzi:"机场", pinyin:"jīchǎng", meaning:"airport", literal:"machine + field / place" },
  { hanzi:"教室", pinyin:"jiàoshì", meaning:"classroom", literal:"teach + room" },
  { hanzi:"房间", pinyin:"fángjiān", meaning:"room", literal:"house + between / space" },
  { hanzi:"路", pinyin:"lù", meaning:"road" },
  { hanzi:"左边", pinyin:"zuǒbiān", meaning:"left side", literal:"left + side" },
  { hanzi:"右边", pinyin:"yòubiān", meaning:"right side", literal:"right + side" },
  { hanzi:"外", pinyin:"wài", meaning:"outside" },
  { hanzi:"旁边", pinyin:"pángbiān", meaning:"next to / side", literal:"side + side" },
  { hanzi:"里面", pinyin:"lǐmiàn", meaning:"inside", literal:"inside + face / side" },
  { hanzi:"早上", pinyin:"zǎoshang", meaning:"morning", literal:"early + up / on" },
  { hanzi:"晚上", pinyin:"wǎnshang", meaning:"evening", literal:"late + up / on" },
  { hanzi:"小时", pinyin:"xiǎoshí", meaning:"hour", literal:"small + time" },
  { hanzi:"时间", pinyin:"shíjiān", meaning:"time", literal:"time + between" },
  { hanzi:"去年", pinyin:"qùnián", meaning:"last year", literal:"go / past + year" },
  { hanzi:"号", pinyin:"hào", meaning:"number / date" },
  { hanzi:"生日", pinyin:"shēngrì", meaning:"birthday", literal:"birth + day" },
  { hanzi:"哥哥", pinyin:"gēge", meaning:"older brother", literal:"older brother (doubled)" },
  { hanzi:"姐姐", pinyin:"jiějie", meaning:"older sister", literal:"older sister (doubled)" },
  { hanzi:"弟弟", pinyin:"dìdi", meaning:"younger brother", literal:"younger brother (doubled)" },
  { hanzi:"妹妹", pinyin:"mèimei", meaning:"younger sister", literal:"younger sister (doubled)" },
  { hanzi:"丈夫", pinyin:"zhàngfu", meaning:"husband", literal:"elder / unit + man" },
  { hanzi:"妻子", pinyin:"qīzi", meaning:"wife", literal:"wife + (noun suffix)" },
  { hanzi:"孩子", pinyin:"háizi", meaning:"child", literal:"child + (noun suffix)" },
  { hanzi:"男人", pinyin:"nánrén", meaning:"man", literal:"male + person" },
  { hanzi:"女人", pinyin:"nǚrén", meaning:"woman", literal:"female + person" },
  { hanzi:"服务员", pinyin:"fúwùyuán", meaning:"waiter / attendant", literal:"serve + affair + member" },
  { hanzi:"鱼", pinyin:"yú", meaning:"fish" },
  { hanzi:"羊肉", pinyin:"yángròu", meaning:"mutton", literal:"sheep + meat" },
  { hanzi:"牛奶", pinyin:"niúnǎi", meaning:"milk", literal:"cow + milk" },
  { hanzi:"鸡蛋", pinyin:"jīdàn", meaning:"egg", literal:"chicken + egg" },
  { hanzi:"西瓜", pinyin:"xīguā", meaning:"watermelon", literal:"west + melon" },
  { hanzi:"咖啡", pinyin:"kāfēi", meaning:"coffee", literal:"phonetic loanword (coffee)" },
  { hanzi:"自行车", pinyin:"zìxíngchē", meaning:"bicycle", literal:"self + go / walk + vehicle" },
  { hanzi:"船", pinyin:"chuán", meaning:"boat" },
  { hanzi:"雪", pinyin:"xuě", meaning:"snow" },
  { hanzi:"药", pinyin:"yào", meaning:"medicine" },
  { hanzi:"手机", pinyin:"shǒujī", meaning:"cell phone", literal:"hand + machine" },
  { hanzi:"手表", pinyin:"shǒubiǎo", meaning:"wristwatch", literal:"hand + watch / gauge" },
  { hanzi:"眼睛", pinyin:"yǎnjīng", meaning:"eye", literal:"eye + eyeball" },
  { hanzi:"身体", pinyin:"shēntǐ", meaning:"body", literal:"body + body" },
  { hanzi:"公共汽车", pinyin:"gōnggòngqìchē", meaning:"bus", literal:"public + together + steam / gas + vehicle" },
  { hanzi:"报纸", pinyin:"bàozhǐ", meaning:"newspaper", literal:"report + paper" },
  { hanzi:"门", pinyin:"mén", meaning:"door" },
  { hanzi:"题", pinyin:"tí", meaning:"question / topic" },
  { hanzi:"课", pinyin:"kè", meaning:"lesson / class" },
  { hanzi:"姓", pinyin:"xìng", meaning:"surname" },
  { hanzi:"问题", pinyin:"wèntí", meaning:"question / problem", literal:"ask + topic" },
  { hanzi:"事情", pinyin:"shìqing", meaning:"matter / affair", literal:"matter + feeling / affair" },
  { hanzi:"考试", pinyin:"kǎoshì", meaning:"exam", literal:"test + try" },
  { hanzi:"票", pinyin:"piào", meaning:"ticket" },
  { hanzi:"意思", pinyin:"yìsi", meaning:"meaning", literal:"idea + think" },
  { hanzi:"颜色", pinyin:"yánsè", meaning:"color", literal:"face / countenance + color" },
  { hanzi:"欢迎", pinyin:"huānyíng", meaning:"welcome", literal:"joyful + greet" },
  { hanzi:"问", pinyin:"wèn", meaning:"to ask" },
  { hanzi:"走", pinyin:"zǒu", meaning:"to walk" },
  { hanzi:"进", pinyin:"jìn", meaning:"to enter" },
  { hanzi:"出", pinyin:"chū", meaning:"to exit" },
  { hanzi:"跑步", pinyin:"pǎobù", meaning:"to run / jog", literal:"run + step" },
  { hanzi:"到", pinyin:"dào", meaning:"to arrive" },
  { hanzi:"穿", pinyin:"chuān", meaning:"to wear" },
  { hanzi:"洗", pinyin:"xǐ", meaning:"to wash" },
  { hanzi:"给", pinyin:"gěi", meaning:"to give" },
  { hanzi:"找", pinyin:"zhǎo", meaning:"to look for" },
  { hanzi:"懂", pinyin:"dǒng", meaning:"to understand" },
  { hanzi:"笑", pinyin:"xiào", meaning:"to laugh / smile" },
  { hanzi:"回答", pinyin:"huídá", meaning:"to answer", literal:"return + answer" },
  { hanzi:"告诉", pinyin:"gàosù", meaning:"to tell", literal:"tell + tell / complain" },
  { hanzi:"准备", pinyin:"zhǔnbèi", meaning:"to prepare", literal:"allow / standard + prepare" },
  { hanzi:"开始", pinyin:"kāishǐ", meaning:"to begin", literal:"open + begin" },
  { hanzi:"介绍", pinyin:"jièshào", meaning:"to introduce", literal:"between + continue / carry on" },
  { hanzi:"帮助", pinyin:"bāngzhù", meaning:"to help", literal:"help + help" },
  { hanzi:"玩", pinyin:"wán", meaning:"to play" },
  { hanzi:"送", pinyin:"sòng", meaning:"to give (a gift) / see off" },
  { hanzi:"等", pinyin:"děng", meaning:"to wait" },
  { hanzi:"让", pinyin:"ràng", meaning:"to let / allow" },
  { hanzi:"起床", pinyin:"qǐchuáng", meaning:"to get up", literal:"rise + bed" },
  { hanzi:"唱歌", pinyin:"chànggē", meaning:"to sing", literal:"sing + song" },
  { hanzi:"跳舞", pinyin:"tiàowǔ", meaning:"to dance", literal:"jump + dance" },
  { hanzi:"旅游", pinyin:"lǚyóu", meaning:"to travel", literal:"travel + roam" },
  { hanzi:"上班", pinyin:"shàngbān", meaning:"to go to work", literal:"up / on + shift / duty" },
  { hanzi:"生病", pinyin:"shēngbìng", meaning:"to fall ill", literal:"produce / develop + sickness" },
  { hanzi:"休息", pinyin:"xiūxi", meaning:"to rest", literal:"rest + breath / rest" },
  { hanzi:"运动", pinyin:"yùndòng", meaning:"to exercise", literal:"move / carry + move" },
  { hanzi:"游泳", pinyin:"yóuyǒng", meaning:"to swim", literal:"swim + swim" },
  { hanzi:"踢足球", pinyin:"tī zúqiú", meaning:"to play soccer", literal:"kick + foot + ball" },
  { hanzi:"打篮球", pinyin:"dǎ lánqiú", meaning:"to play basketball", literal:"hit / play + basket + ball" },
  { hanzi:"完", pinyin:"wán", meaning:"to finish" },
  { hanzi:"觉得", pinyin:"juéde", meaning:"to feel / think", literal:"feel + get / obtain" },
  { hanzi:"知道", pinyin:"zhīdào", meaning:"to know", literal:"know + way / path" },
  { hanzi:"希望", pinyin:"xīwàng", meaning:"to hope", literal:"hope + look towards / hope" },
  { hanzi:"可以", pinyin:"kěyǐ", meaning:"can / may", literal:"can + by means of" },
  { hanzi:"要", pinyin:"yào", meaning:"to want / need" },
  { hanzi:"可能", pinyin:"kěnéng", meaning:"maybe / possibly", literal:"can + able" },
  { hanzi:"高", pinyin:"gāo", meaning:"tall" },
  { hanzi:"红", pinyin:"hóng", meaning:"red" },
  { hanzi:"白", pinyin:"bái", meaning:"white" },
  { hanzi:"黑", pinyin:"hēi", meaning:"black" },
  { hanzi:"忙", pinyin:"máng", meaning:"busy" },
  { hanzi:"快", pinyin:"kuài", meaning:"fast" },
  { hanzi:"慢", pinyin:"màn", meaning:"slow" },
  { hanzi:"远", pinyin:"yuǎn", meaning:"far" },
  { hanzi:"近", pinyin:"jìn", meaning:"close / near" },
  { hanzi:"好吃", pinyin:"hǎochī", meaning:"delicious", literal:"good + eat" },
  { hanzi:"累", pinyin:"lèi", meaning:"tired" },
  { hanzi:"长", pinyin:"cháng", meaning:"long" },
  { hanzi:"新", pinyin:"xīn", meaning:"new" },
  { hanzi:"贵", pinyin:"guì", meaning:"expensive" },
  { hanzi:"便宜", pinyin:"piányi", meaning:"cheap", literal:"convenient + suitable" },
  { hanzi:"晴", pinyin:"qíng", meaning:"clear / sunny" },
  { hanzi:"阴", pinyin:"yīn", meaning:"cloudy / overcast" },
  { hanzi:"错", pinyin:"cuò", meaning:"wrong" },
  { hanzi:"快乐", pinyin:"kuàilè", meaning:"happy", literal:"fast / pleased + happy / music" },
];

// Combined dictionary for pinyin autocomplete, deduped by hanzi.
export const DICTIONARY = (function(){
  const seen = new Set();
  const combined = [];
  [...SEED, ...IMPORT_BATCH_1, ...EXTRA_DICT, ...EXTRA_DICT2].forEach(entry => {
    if(!seen.has(entry.hanzi)){ seen.add(entry.hanzi); combined.push(entry); }
  });
  return combined;
})();

export const CHAR_MEANINGS = {
  "你":"you", "好":"good", "谢":"thank", "朋":"friend", "友":"friend",
  "学":"study", "习":"practice", "时":"time", "间":"between", "明":"bright",
  "天":"sky / day", "喜":"happy", "欢":"joyful", "工":"work", "作":"do / make",
  "我":"I / me", "他":"he", "她":"she", "它":"it", "的":"'s (possessive)",
  "个":"(counter)", "人":"person", "是":"to be", "不":"not", "爱":"love",
  "一":"one", "早":"early", "晚":"late", "安":"peace", "在":"at / located",
  "了":"(completed)", "们":"(plural)", "有":"have", "大":"big", "之":"'s (formal)",
  "这":"this", "为":"for", "日":"sun / day", "太":"too / very", "阳":"sun",
  "月":"moon / month", "那":"that", "谁":"who", "室":"room", "老":"old",
  "师":"teacher / master", "男":"male", "女":"female", "名":"name", "字":"character / word",
  "叫":"call", "什":"what", "么":"(particle)", "请":"please", "问":"ask",
  "对":"correct / facing", "起":"rise", "没":"not have", "关":"close / relate",
  "系":"relate / system", "同":"same", "客":"guest", "气":"air / spirit",
  "快":"fast / happy", "乐":"happy / music", "米":"rice", "饭":"cooked rice / meal",
  "火":"fire", "水":"water", "篮":"basket", "球":"ball", "龙":"dragon",
  "恐":"fear", "亮":"bright", "生":"life / student", "高":"tall / high",
  "兴":"excited", "很":"very", "会":"can / meeting", "说":"speak", "家":"home",
  "口":"mouth", "和":"and", "年":"year", "妈":"mother", "爸":"father",
  "儿":"son / child", "子":"child (suffix)", "猫":"cat", "狗":"dog",
  "书":"book", "笔":"pen", "桌":"table", "椅":"chair", "车":"vehicle",
  "飞":"fly", "机":"machine", "自":"self", "行":"go / walk / okay",
  "校":"school", "医":"medicine / doctor", "院":"institution / yard",
  "商":"commerce", "店":"shop", "公":"public", "司":"manage / company",
  "电":"electric", "话":"words / speech", "脑":"brain", "视":"look / vision",
  "手":"hand", "衣":"clothes", "服":"clothes / serve", "鞋":"shoe", "钱":"money",
  "今":"now / present", "昨":"yesterday", "现":"now / present", "星":"star",
  "期":"period", "上":"up / on", "中":"middle", "午":"noon", "吃":"eat",
  "喝":"drink", "睡":"sleep", "觉":"sleep / sense", "看":"look", "听":"listen",
  "走":"walk", "跑":"run", "跳":"jump", "笑":"laugh", "哭":"cry",
  "矮":"short (height)", "胖":"fat", "瘦":"thin", "漂":"float / pretty",
  "帅":"handsome", "新":"new", "旧":"old (object)", "多":"many", "少":"few",
  "冷":"cold", "热":"hot", "下":"down / under", "雨":"rain", "颜":"color / face",
  "色":"color", "红":"red", "黑":"black", "白":"white", "蓝":"blue",
  "绿":"green", "黄":"yellow", "二":"two", "三":"three", "四":"four",
  "五":"five", "六":"six", "七":"seven", "八":"eight", "九":"nine",
  "十":"ten", "零":"zero", "百":"hundred", "千":"thousand", "万":"ten-thousand",
  "左":"left", "右":"right", "前":"front", "后":"back", "里":"inside",
  "外":"outside", "东":"east", "西":"west", "南":"south", "北":"north",
  "国":"country", "城":"city", "市":"city / market", "头":"head", "眼":"eye",
  "睛":"eyeball", "耳":"ear", "朵":"(counter for ears/flowers)", "鼻":"nose",
  "嘴":"mouth", "脚":"foot", "心":"heart", "去":"go", "来":"come",
  "写":"write", "读":"read", "买":"buy", "卖":"sell", "给":"give",
  "做":"do / make", "坐":"sit", "站":"stand / station", "开":"open",
  "穿":"wear", "用":"use", "玩":"play", "唱":"sing", "歌":"song",
  "舞":"dance", "休":"rest", "息":"rest / breath", "帮":"help", "助":"help",
  "长":"long", "短":"short (length)", "慢":"slow", "贵":"expensive",
  "便":"convenient / cheap", "宜":"suitable / cheap", "干":"dry / do",
  "净":"clean", "脏":"dirty", "容":"contain / allow", "易":"easy / change",
  "难":"difficult", "忙":"busy", "累":"tired", "饿":"hungry", "渴":"thirsty",
  "怎":"how", "哪":"which", "几":"how many", "房":"house / room", "门":"door",
  "窗":"window", "户":"household / door", "床":"bed", "菜":"vegetable / dish",
  "茶":"tea", "咖":"(coffee)", "啡":"(coffee)", "牛":"cow / ox", "奶":"milk",
  "面":"flour / noodle / face", "包":"wrap / bag", "苹":"(apple)", "果":"fruit / result",
  "香":"fragrant", "蕉":"(banana)", "瓜":"melon", "样":"kind / appearance",
  "岁":"years old (age)", "本":"root / (book counter)", "些":"some",
  "块":"piece / lump", "都":"all / both", "吗":"(question)", "呢":"(question)",
  "喂":"hey / hello", "京":"capital", "点":"dot / o'clock", "分":"divide / minute",
  "钟":"clock / bell", "候":"wait / time", "先":"first", "小":"small",
  "姐":"older sister / miss", "杯":"cup", "出":"exit / go out", "租":"rent",
  "影":"shadow / movie", "汉":"Han (Chinese)", "语":"language", "再":"again",
  "见":"see", "回":"return", "打":"hit / do", "住":"live / reside",
  "想":"think / want", "认":"recognize", "识":"know / knowledge", "能":"can / able"
};

export function literalBreakdown(hanzi){
  if(!hanzi || hanzi.length < 2) return null;
  const parts = [];
  for(const ch of hanzi){
    const gloss = CHAR_MEANINGS[ch];
    if(!gloss) return null;
    parts.push(gloss);
  }
  return parts.join(' + ');
}

export function toneless(str){
  return (str || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[0-9]/g, '').toLowerCase();
}
export function tonelessCompact(str){
  return toneless(str).replace(/[\s\-']/g, '');
}

export const Store = {
  async get(key){
    if(typeof window !== 'undefined' && window.storage){
      try{ return await window.storage.get(key, false); }catch(err){ return null; }
    }
    try{
      const raw = localStorage.getItem('hanzi_' + key);
      return raw === null ? null : { key, value: raw, shared: false };
    }catch(err){ return null; }
  },
  async set(key, value){
    if(typeof window !== 'undefined' && window.storage){
      try{ return await window.storage.set(key, value, false); }catch(err){ return null; }
    }
    try{ localStorage.setItem('hanzi_' + key, value); return { key, value, shared: false }; }catch(err){ return null; }
  }
};

export function uid(){ return 'c' + Date.now().toString(36) + Math.random().toString(36).slice(2,7); }

export function newCard(hanzi, pinyin, meaning, deck, literal){
  return { id: uid(), hanzi, pinyin, meaning, deck: (deck || 'General'), literal: (literal || '').trim(), suspended: false, learned: false, learnedAt: null, ease: 2.5, interval: 0, reps: 0, due: Date.now(), created: Date.now() };
}

export const DAY = 86400000;
const MINUTE = 60000;

export function schedule(card, rating){
  const now = Date.now();
  if(rating === 'again'){ card.reps = 0; card.interval = 0; card.due = now + 2 * MINUTE; }
  else if(rating === 'hard'){ card.interval = 10 * MINUTE / DAY; card.due = now + 10 * MINUTE; card.reps += 1; }
  else if(rating === 'good'){ card.interval = 1; card.due = now + 1 * DAY; card.reps += 1; }
  else if(rating === 'easy'){ card.interval = 3; card.due = now + 3 * DAY; card.reps += 1; }
}

export function previewInterval(card, rating){
  const clone = JSON.parse(JSON.stringify(card));
  schedule(clone, rating);
  const ms = clone.due - Date.now();
  const mins = Math.round(ms / MINUTE);
  if(mins < 60) return mins + ' min';
  const hours = Math.round(mins / 60);
  if(hours < 24) return hours + ' hr';
  const days = Math.round(hours / 24);
  if(days === 1) return '1 day';
  if(days < 30) return days + ' days';
  if(days < 365) return Math.round(days/30) + ' mo';
  return Math.round(days/365) + ' yr';
}

export function dueIn(ms){
  const days = Math.round(ms / DAY);
  if(days <= 0) return 'due now';
  if(days === 1) return 'in 1 day';
  if(days < 30) return 'in ' + days + ' days';
  return 'in ' + Math.round(days/30) + ' mo';
}

export const SENTENCE_BANK = [
  { zh:"我是学生。", pinyin:"wǒ shì xué shēng.", en:"I am a student.", words:["我","是","学生"] },
  { zh:"你好吗？", pinyin:"nǐ hǎo ma?", en:"How are you?", words:["你好","吗"] },
  { zh:"我很高兴认识你。", pinyin:"wǒ hěn gāo xìng rèn shi nǐ.", en:"I'm very happy to meet you.", words:["我","很","高兴","认识","你"] },
  { zh:"他是我的朋友。", pinyin:"tā shì wǒ de péng yǒu.", en:"He is my friend.", words:["他","是","我","的","朋友"] },
  { zh:"今天天气很好。", pinyin:"jīn tiān tiān qì hěn hǎo.", en:"The weather is nice today.", words:["今天","天气","很","好"] },
  { zh:"我喜欢喝茶。", pinyin:"wǒ xǐ huān hē chá.", en:"I like drinking tea.", words:["我","喜欢","喝","茶"] },
  { zh:"你叫什么名字？", pinyin:"nǐ jiào shén me míng zi?", en:"What's your name?", words:["你","叫","什么","名字"] },
  { zh:"我们去学校。", pinyin:"wǒ men qù xué xiào.", en:"We're going to school.", words:["我们","去","学校"] },
  { zh:"现在几点？", pinyin:"xiàn zài jǐ diǎn?", en:"What time is it now?", words:["现在","几","点"] },
  { zh:"我爱我的家。", pinyin:"wǒ ài wǒ de jiā.", en:"I love my home.", words:["我","爱","的","家"] },
  { zh:"谢谢你，再见。", pinyin:"xiè xiè nǐ, zài jiàn.", en:"Thank you, goodbye.", words:["谢谢","你","再见"] },
  { zh:"对不起，我错了。", pinyin:"duì bu qǐ, wǒ cuò le.", en:"Sorry, I was wrong.", words:["对不起","我","错","了"] },
  { zh:"他在家吗？", pinyin:"tā zài jiā ma?", en:"Is he home?", words:["他","在","家","吗"] },
  { zh:"我妈妈是医生。", pinyin:"wǒ mā ma shì yī shēng.", en:"My mom is a doctor.", words:["我","妈妈","是","医生"] },
  { zh:"这是我的书。", pinyin:"zhè shì wǒ de shū.", en:"This is my book.", words:["这","是","我","的","书"] },
  { zh:"你想吃什么？", pinyin:"nǐ xiǎng chī shén me?", en:"What do you want to eat?", words:["你","想","吃","什么"] },
  { zh:"我们是同学。", pinyin:"wǒ men shì tóng xué.", en:"We are classmates.", words:["我们","是","同学"] },
  { zh:"明天再见。", pinyin:"míng tiān zài jiàn.", en:"See you tomorrow.", words:["明天","再见"] },
  { zh:"我很忙，没有时间。", pinyin:"wǒ hěn máng, méi yǒu shí jiān.", en:"I'm busy, I have no time.", words:["我","很","忙","没","有","时间"] },
  { zh:"天气很冷。", pinyin:"tiān qì hěn lěng.", en:"The weather is cold.", words:["天气","很","冷"] },
  { zh:"这个苹果很好吃。", pinyin:"zhè ge píng guǒ hěn hǎo chī.", en:"This apple is delicious.", words:["这","个","苹果","很","好吃"] },
  { zh:"我每天学习汉语。", pinyin:"wǒ měi tiān xué xí hàn yǔ.", en:"I study Chinese every day.", words:["我","每天","学习","汉语"] },
  { zh:"你的猫很漂亮。", pinyin:"nǐ de māo hěn piào liang.", en:"Your cat is beautiful.", words:["你","的","猫","很","漂亮"] },
  { zh:"他每天运动。", pinyin:"tā měi tiān yùn dòng.", en:"He exercises every day.", words:["他","每天","运动"] },
  { zh:"我们一起去看电影。", pinyin:"wǒ men yì qǐ qù kàn diàn yǐng.", en:"Let's go watch a movie together.", words:["我们","一起","去","看","电影"] },
  { zh:"这是什么意思？", pinyin:"zhè shì shén me yì si?", en:"What does this mean?", words:["这","是","什么","意思"] },
  { zh:"我觉得很好。", pinyin:"wǒ jué de hěn hǎo.", en:"I think it's good.", words:["我","觉得","很","好"] },
  { zh:"你会说汉语吗？", pinyin:"nǐ huì shuō hàn yǔ ma?", en:"Can you speak Chinese?", words:["你","会","说","汉语","吗"] },
  { zh:"我想休息。", pinyin:"wǒ xiǎng xiū xi.", en:"I want to rest.", words:["我","想","休息"] },
  { zh:"他很聪明。", pinyin:"tā hěn cōng ming.", en:"He is very smart.", words:["他","很","聪明"] },
];

export const SENTENCE_BANK_2 = [
  { zh:"不好意思，请问洗手间在哪儿？", pinyin:"bù hǎo yì si, qǐng wèn xǐ shǒu jiān zài nǎr?", en:"Excuse me, where's the restroom?" },
  { zh:"你说的对，我没想到这一点。", pinyin:"nǐ shuō de duì, wǒ méi xiǎng dào zhè yì diǎn.", en:"You're right, I didn't think of that." },
  { zh:"没事儿，下次注意就行了。", pinyin:"méi shìr, xià cì zhù yì jiù xíng le.", en:"It's fine, just be careful next time." },
  { zh:"这附近有没有好一点的餐厅？", pinyin:"zhè fù jìn yǒu méi yǒu hǎo yì diǎn de cān tīng?", en:"Is there a decent restaurant near here?" },
  { zh:"我最近特别忙，都没时间休息。", pinyin:"wǒ zuì jìn tè bié máng, dōu méi shí jiān xiū xi.", en:"I've been really busy lately, no time to rest at all." },
  { zh:"你先别急，我们再想想办法。", pinyin:"nǐ xiān bié jí, wǒ men zài xiǎng xiǎng bàn fǎ.", en:"Don't rush, let's think of another way." },
  { zh:"这个多少钱？能不能便宜点儿？", pinyin:"zhè ge duō shǎo qián? néng bu néng pián yi diǎnr?", en:"How much is this? Can you make it a little cheaper?" },
  { zh:"你放心吧，这件事交给我了。", pinyin:"nǐ fàng xīn ba, zhè jiàn shì jiāo gěi wǒ le.", en:"Don't worry, leave this to me." },
  { zh:"我今天有点儿不舒服，可能感冒了。", pinyin:"wǒ jīn tiān yǒu diǎnr bù shū fu, kě néng gǎn mào le.", en:"I feel a bit unwell today, I might have a cold." },
  { zh:"你要不要一起吃饭？我请客。", pinyin:"nǐ yào bu yào yì qǐ chī fàn? wǒ qǐng kè.", en:"Do you want to eat together? It's my treat." },
  { zh:"路上小心，到了给我发个消息。", pinyin:"lù shang xiǎo xīn, dào le gěi wǒ fā ge xiāo xi.", en:"Be careful on the way, text me when you arrive." },
  { zh:"这件事说来话长，我们坐下来聊吧。", pinyin:"zhè jiàn shì shuō lái huà cháng, wǒ men zuò xià lái liáo ba.", en:"It's a long story, let's sit down and talk." },
  { zh:"你别开玩笑了，我是认真的。", pinyin:"nǐ bié kāi wán xiào le, wǒ shì rèn zhēn de.", en:"Stop joking, I'm serious." },
  { zh:"我们好久没见了，找时间聚一聚吧。", pinyin:"wǒ men hǎo jiǔ méi jiàn le, zhǎo shí jiān jù yi jù ba.", en:"We haven't seen each other in ages, let's get together sometime." },
  { zh:"这附近堵车堵得厉害，你早点儿出发吧。", pinyin:"zhè fù jìn dǔ chē dǔ de lì hai, nǐ zǎo diǎnr chū fā ba.", en:"Traffic is really bad around here, you should leave early." },
  { zh:"我随便看看，谢谢。", pinyin:"wǒ suí biàn kàn kan, xiè xie.", en:"I'm just browsing, thanks." },
  { zh:"你辛苦了，先坐下休息一会儿吧。", pinyin:"nǐ xīn kǔ le, xiān zuò xià xiū xi yí huìr ba.", en:"You've worked hard, sit down and rest for a bit." },
  { zh:"这道题我不太明白，你能给我讲讲吗？", pinyin:"zhè dào tí wǒ bú tài míng bai, nǐ néng gěi wǒ jiǎng jiang ma?", en:"I don't quite understand this question, can you explain it to me?" },
  { zh:"你今天怎么这么晚才回来？", pinyin:"nǐ jīn tiān zěn me zhè me wǎn cái huí lai?", en:"Why did you come back so late today?" },
  { zh:"我们时间不多了，快点儿走吧。", pinyin:"wǒ men shí jiān bù duō le, kuài diǎnr zǒu ba.", en:"We don't have much time left, let's hurry." },
  { zh:"你要是不舒服，就早点儿去看医生。", pinyin:"nǐ yào shi bù shū fu, jiù zǎo diǎnr qù kàn yī shēng.", en:"If you're not feeling well, go see a doctor soon." },
  { zh:"这家店的东西又贵又不好吃，别去了。", pinyin:"zhè jiā diàn de dōng xi yòu guì yòu bù hǎo chī, bié qù le.", en:"This shop's food is expensive and not tasty, let's not go there." },
  { zh:"你别管我了，我自己能解决。", pinyin:"nǐ bié guǎn wǒ le, wǒ zì jǐ néng jiě jué.", en:"Don't worry about me, I can handle it myself." },
  { zh:"我们出去走走吧，一直待在家里太闷了。", pinyin:"wǒ men chū qu zǒu zou ba, yì zhí dāi zài jiā li tài mēn le.", en:"Let's go out for a walk, staying home all the time is too stuffy." },
  { zh:"你听我说完，事情不是你想的那样。", pinyin:"nǐ tīng wǒ shuō wán, shì qing bú shì nǐ xiǎng de nà yàng.", en:"Let me finish, things aren't what you think." },
  { zh:"没关系，谁都会犯错，下次改就好了。", pinyin:"méi guān xi, shéi dōu huì fàn cuò, xià cì gǎi jiù hǎo le.", en:"It's okay, everyone makes mistakes, just fix it next time." },
  { zh:"你可别忘了明天的约会。", pinyin:"nǐ kě bié wàng le míng tiān de yuē huì.", en:"Don't you forget about tomorrow's appointment." },
  { zh:"这几天太累了，我想在家好好睡一觉。", pinyin:"zhè jǐ tiān tài lèi le, wǒ xiǎng zài jiā hǎo hǎo shuì yí jiào.", en:"I've been so tired these past few days, I want to sleep well at home." },
  { zh:"你说得容易，做起来可没那么简单。", pinyin:"nǐ shuō de róng yì, zuò qǐ lái kě méi nà me jiǎn dān.", en:"It's easy to say, but not that simple to do." },
  { zh:"算了吧，别为这点小事生气了。", pinyin:"suàn le ba, bié wèi zhè diǎn xiǎo shì shēng qì le.", en:"Forget it, don't get angry over such a small thing." },
];

export const IMPORT_BATCH_SENTENCES_2 = SENTENCE_BANK_2.map(s => ({ hanzi: s.zh, pinyin: s.pinyin, meaning: s.en }));

export const IMPORT_BATCH_SENTENCES = SENTENCE_BANK.map(s => ({ hanzi: s.zh, pinyin: s.pinyin, meaning: s.en }));

export async function runImportBatch(cards, batch, flagKey, deck){
  try{
    const flag = await Store.get(flagKey);
    if(flag && flag.value === "true") return 0;
  }catch(err){ /* proceed */ }
  const existingHanzi = new Set(cards.map(c => c.hanzi));
  let added = 0;
  batch.forEach(item => {
    if(!existingHanzi.has(item.hanzi)){
      cards.push(newCard(item.hanzi, item.pinyin, item.meaning, deck || 'General', item.literal));
      existingHanzi.add(item.hanzi);
      added++;
    }
  });
  await Store.set(flagKey, "true");
  return added;
}

export const IMPORT_BATCH_2 = [
  { hanzi:"帮忙", pinyin:"bāng máng", meaning:"to help", literal:"help + busy" },
  { hanzi:"办法", pinyin:"bàn fǎ", meaning:"method / way", literal:"handle + law/method" },
  { hanzi:"办公室", pinyin:"bàn gōng shì", meaning:"office", literal:"handle + public + room" },
  { hanzi:"半", pinyin:"bàn", meaning:"half" },
  { hanzi:"班", pinyin:"bān", meaning:"class" },
  { hanzi:"搬", pinyin:"bān", meaning:"to move" },
  { hanzi:"办", pinyin:"bàn", meaning:"to handle" },
  { hanzi:"包", pinyin:"bāo", meaning:"bag / to wrap" },
  { hanzi:"饱", pinyin:"bǎo", meaning:"full (from eating)" },
  { hanzi:"保护", pinyin:"bǎo hù", meaning:"to protect", literal:"protect + protect" },
  { hanzi:"报名", pinyin:"bào míng", meaning:"to sign up", literal:"report + name" },
  { hanzi:"杯", pinyin:"bēi", meaning:"cup (measure word)" },
  { hanzi:"北方", pinyin:"běi fāng", meaning:"north", literal:"north + direction" },
  { hanzi:"被", pinyin:"bèi", meaning:"by (passive marker)" },
  { hanzi:"笨", pinyin:"bèn", meaning:"stupid" },
  { hanzi:"比", pinyin:"bǐ", meaning:"to compare" },
  { hanzi:"比较", pinyin:"bǐ jiào", meaning:"relatively", literal:"compare + compare" },
  { hanzi:"比如", pinyin:"bǐ rú", meaning:"for example", literal:"compare + like/as" },
  { hanzi:"必须", pinyin:"bì xū", meaning:"must", literal:"must + must" },
  { hanzi:"变化", pinyin:"biàn huà", meaning:"change", literal:"change + transform" },
  { hanzi:"表示", pinyin:"biǎo shì", meaning:"to express", literal:"express + show" },
  { hanzi:"表演", pinyin:"biǎo yǎn", meaning:"to perform", literal:"express + perform" },
  { hanzi:"别人", pinyin:"bié rén", meaning:"other people", literal:"other/don't + person" },
  { hanzi:"冰箱", pinyin:"bīng xiāng", meaning:"refrigerator", literal:"ice + box" },
  { hanzi:"博物馆", pinyin:"bó wù guǎn", meaning:"museum", literal:"broad + thing + building" },
  { hanzi:"不但", pinyin:"bù dàn", meaning:"not only", literal:"not + but" },
  { hanzi:"部分", pinyin:"bù fen", meaning:"part / portion", literal:"part/section + divide/part" },
  { hanzi:"擦", pinyin:"cā", meaning:"to wipe" },
  { hanzi:"猜", pinyin:"cāi", meaning:"to guess" },
  { hanzi:"才", pinyin:"cái", meaning:"only then" },
  { hanzi:"菜单", pinyin:"cài dān", meaning:"menu", literal:"dish/vegetable + single/list" },
  { hanzi:"参加", pinyin:"cān jiā", meaning:"to participate", literal:"take part + add" },
  { hanzi:"餐厅", pinyin:"cān tīng", meaning:"restaurant", literal:"meal + hall" },
  { hanzi:"草", pinyin:"cǎo", meaning:"grass" },
  { hanzi:"层", pinyin:"céng", meaning:"floor / layer" },
  { hanzi:"差", pinyin:"chà", meaning:"poor / lacking" },
  { hanzi:"长城", pinyin:"cháng chéng", meaning:"the Great Wall", literal:"long/grow + city wall" },
  { hanzi:"场", pinyin:"chǎng", meaning:"field / venue" },
  { hanzi:"唱", pinyin:"chàng", meaning:"to sing" },
  { hanzi:"超市", pinyin:"chāo shì", meaning:"supermarket", literal:"exceed + market" },
  { hanzi:"衬衫", pinyin:"chèn shān", meaning:"shirt", literal:"lining + shirt" },
  { hanzi:"成绩", pinyin:"chéng jì", meaning:"grade / score", literal:"become + achievement" },
  { hanzi:"成功", pinyin:"chéng gōng", meaning:"success", literal:"become + skill/merit" },
  { hanzi:"迟到", pinyin:"chí dào", meaning:"to be late", literal:"late + arrive" },
  { hanzi:"出发", pinyin:"chū fā", meaning:"to set off", literal:"go out + emit/send" },
  { hanzi:"出生", pinyin:"chū shēng", meaning:"to be born", literal:"go out + life/birth" },
  { hanzi:"出现", pinyin:"chū xiàn", meaning:"to appear", literal:"go out + present/appear" },
  { hanzi:"厨房", pinyin:"chú fáng", meaning:"kitchen", literal:"kitchen + house/room" },
  { hanzi:"除了", pinyin:"chú le", meaning:"besides / except", literal:"remove/except + (completed-action particle)" },
  { hanzi:"穿过", pinyin:"chuān guò", meaning:"to pass through", literal:"wear/pass through + pass" },
  { hanzi:"船票", pinyin:"chuán piào", meaning:"boat ticket", literal:"boat + ticket" },
  { hanzi:"春天", pinyin:"chūn tiān", meaning:"spring", literal:"spring + day/sky" },
  { hanzi:"词语", pinyin:"cí yǔ", meaning:"word / term", literal:"word + language" },
  { hanzi:"聪明", pinyin:"cōng ming", meaning:"smart", literal:"sharp-eared + bright" },
  { hanzi:"从来", pinyin:"cóng lái", meaning:"always / never (with negative)", literal:"from + come" },
  { hanzi:"错误", pinyin:"cuò wù", meaning:"mistake", literal:"wrong + mistake" },
  { hanzi:"打扫", pinyin:"dǎ sǎo", meaning:"to clean", literal:"hit/do + sweep" },
  { hanzi:"打算", pinyin:"dǎ suàn", meaning:"to plan", literal:"hit/do + calculate" },
  { hanzi:"打折", pinyin:"dǎ zhé", meaning:"to give a discount", literal:"hit + discount/fold" },
  { hanzi:"大概", pinyin:"dà gài", meaning:"probably", literal:"big + approximately" },
  { hanzi:"大使馆", pinyin:"dà shǐ guǎn", meaning:"embassy", literal:"big + envoy + building" },
  { hanzi:"大声", pinyin:"dà shēng", meaning:"loudly", literal:"big + sound" },
  { hanzi:"带", pinyin:"dài", meaning:"to bring / to carry" },
  { hanzi:"担心", pinyin:"dān xīn", meaning:"to worry", literal:"carry/bear + heart" },
  { hanzi:"蛋糕", pinyin:"dàn gāo", meaning:"cake", literal:"egg + cake" },
  { hanzi:"当然", pinyin:"dāng rán", meaning:"of course", literal:"when/serve as + so/thus" },
  { hanzi:"地方", pinyin:"dì fang", meaning:"place", literal:"ground/place + direction" },
  { hanzi:"地铁", pinyin:"dì tiě", meaning:"subway", literal:"ground/place + iron/rail" },
  { hanzi:"地图", pinyin:"dì tú", meaning:"map", literal:"ground/place + picture/map" },
  { hanzi:"点心", pinyin:"diǎn xīn", meaning:"snack / dessert", literal:"dot/point + heart" },
  { hanzi:"电梯", pinyin:"diàn tī", meaning:"elevator", literal:"electricity + ladder/stairs" },
  { hanzi:"电子邮件", pinyin:"diàn zǐ yóu jiàn", meaning:"email", literal:"electric + tiny/particle + mail + document" },
  { hanzi:"调查", pinyin:"diào chá", meaning:"to investigate", literal:"adjust/investigate + check" },
  { hanzi:"丢", pinyin:"diū", meaning:"to lose" },
  { hanzi:"冬天", pinyin:"dōng tiān", meaning:"winter", literal:"winter + day/sky" },
  { hanzi:"动物", pinyin:"dòng wù", meaning:"animal", literal:"move + thing" },
  { hanzi:"肚子", pinyin:"dù zi", meaning:"belly", literal:"belly + (noun suffix)" },
  { hanzi:"段", pinyin:"duàn", meaning:"segment / paragraph" },
  { hanzi:"锻炼", pinyin:"duàn liàn", meaning:"to exercise", literal:"forge + refine" },
  { hanzi:"队", pinyin:"duì", meaning:"team" },
  { hanzi:"多么", pinyin:"duō me", meaning:"how (exclamatory)", literal:"many + (question suffix)" },
  { hanzi:"饿死", pinyin:"è sǐ", meaning:"starving", literal:"hungry + die" },
  { hanzi:"耳环", pinyin:"ěr huán", meaning:"earrings", literal:"ear + ring/loop" },
  { hanzi:"发烧", pinyin:"fā shāo", meaning:"to have a fever", literal:"emit/send + burn/fever" },
  { hanzi:"发展", pinyin:"fā zhǎn", meaning:"to develop", literal:"emit/send + unfold/develop" },
  { hanzi:"法律", pinyin:"fǎ lǜ", meaning:"law", literal:"law/method + rule/law" },
  { hanzi:"翻译", pinyin:"fān yì", meaning:"to translate", literal:"turn over + translate" },
  { hanzi:"方便", pinyin:"fāng biàn", meaning:"convenient", literal:"direction + convenient" },
  { hanzi:"方法", pinyin:"fāng fǎ", meaning:"method", literal:"direction + law/method" },
  { hanzi:"方向", pinyin:"fāng xiàng", meaning:"direction", literal:"direction + toward" },
  { hanzi:"房东", pinyin:"fáng dōng", meaning:"landlord", literal:"house/room + east" },
  { hanzi:"放假", pinyin:"fàng jià", meaning:"to be on holiday", literal:"release/let go + vacation/fake" },
  { hanzi:"放心", pinyin:"fàng xīn", meaning:"to feel at ease", literal:"release/let go + heart" },
  { hanzi:"份", pinyin:"fèn", meaning:"copy / portion" },
  { hanzi:"丰富", pinyin:"fēng fù", meaning:"rich / abundant", literal:"abundant + rich" },
  { hanzi:"附近", pinyin:"fù jìn", meaning:"nearby", literal:"attach + near" },
  { hanzi:"复习", pinyin:"fù xí", meaning:"to review", literal:"repeat/again + practice" },
  { hanzi:"复杂", pinyin:"fù zá", meaning:"complicated", literal:"repeat/again + mixed/complicated" },
  { hanzi:"改变", pinyin:"gǎi biàn", meaning:"to change", literal:"change/correct + change" },
  { hanzi:"干杯", pinyin:"gān bēi", meaning:"cheers", literal:"do/dry + cup" },
  { hanzi:"感冒", pinyin:"gǎn mào", meaning:"to catch a cold", literal:"feel + emit/risk" },
  { hanzi:"感觉", pinyin:"gǎn jué", meaning:"feeling", literal:"feel + feel/sense" },
  { hanzi:"感谢", pinyin:"gǎn xiè", meaning:"to thank", literal:"feel + thank" },
  { hanzi:"刚才", pinyin:"gāng cái", meaning:"just now", literal:"just now + only then/talent" },
  { hanzi:"高速公路", pinyin:"gāo sù gōng lù", meaning:"highway", literal:"high + speed + public + road" },
  { hanzi:"个子", pinyin:"gè zi", meaning:"height (of a person)", literal:"(measure word) + (noun suffix)" },
  { hanzi:"根据", pinyin:"gēn jù", meaning:"according to", literal:"root/based on + evidence/according to" },
  { hanzi:"跟", pinyin:"gēn", meaning:"with / to follow" },
  { hanzi:"更", pinyin:"gèng", meaning:"even more" },
  { hanzi:"功夫", pinyin:"gōng fu", meaning:"kung fu / free time", literal:"skill/merit + man/husband" },
  { hanzi:"公园", pinyin:"gōng yuán", meaning:"park", literal:"public + garden" },
  { hanzi:"够", pinyin:"gòu", meaning:"enough" },
  { hanzi:"购物", pinyin:"gòu wù", meaning:"to shop", literal:"purchase + thing" },
  { hanzi:"估计", pinyin:"gū jì", meaning:"to estimate", literal:"estimate + count/plan" },
  { hanzi:"鼓励", pinyin:"gǔ lì", meaning:"to encourage", literal:"drum/encourage + encourage" },
  { hanzi:"顾客", pinyin:"gù kè", meaning:"customer", literal:"look after/customer + guest" },
  { hanzi:"故事", pinyin:"gù shi", meaning:"story", literal:"reason/former + matter" },
  { hanzi:"刮风", pinyin:"guā fēng", meaning:"to be windy", literal:"blow (wind)/scrape + wind" },
  { hanzi:"关系", pinyin:"guān xì", meaning:"relationship", literal:"close/relate + connect/tie" },
  { hanzi:"关于", pinyin:"guān yú", meaning:"about / regarding", literal:"close/relate + at/in" },
  { hanzi:"管理", pinyin:"guǎn lǐ", meaning:"to manage", literal:"manage/tube + reason/manage" },
  { hanzi:"逛", pinyin:"guàng", meaning:"to stroll" },
  { hanzi:"规定", pinyin:"guī dìng", meaning:"rule / regulation", literal:"rule + fix/decide" },
  { hanzi:"果汁", pinyin:"guǒ zhī", meaning:"juice", literal:"fruit/result + juice" },
  { hanzi:"过去", pinyin:"guò qù", meaning:"the past", literal:"pass + go" },
  { hanzi:"害怕", pinyin:"hài pà", meaning:"to be afraid", literal:"harm + fear" },
  { hanzi:"害羞", pinyin:"hài xiū", meaning:"shy", literal:"harm + shy" },
  { hanzi:"寒假", pinyin:"hán jià", meaning:"winter vacation", literal:"cold + vacation/fake" },
  { hanzi:"汗", pinyin:"hàn", meaning:"sweat" },
  { hanzi:"行李箱", pinyin:"xíng li xiāng", meaning:"suitcase", literal:"walk + luggage + box" },
  { hanzi:"合适", pinyin:"hé shì", meaning:"suitable", literal:"combine/fit + suitable" },
  { hanzi:"黑板", pinyin:"hēi bǎn", meaning:"blackboard", literal:"black + board" },
  { hanzi:"后来", pinyin:"hòu lái", meaning:"afterward", literal:"after/behind + come" },
  { hanzi:"互相", pinyin:"hù xiāng", meaning:"mutually", literal:"mutual + mutual/appearance" },
  { hanzi:"护士", pinyin:"hù shi", meaning:"nurse", literal:"protect + scholar/officer" },
  { hanzi:"护照", pinyin:"hù zhào", meaning:"passport", literal:"protect + shine/according to" },
  { hanzi:"花", pinyin:"huā", meaning:"flower / to spend" },
  { hanzi:"画", pinyin:"huà", meaning:"to draw" },
  { hanzi:"坏", pinyin:"huài", meaning:"bad / broken" },
  { hanzi:"环境", pinyin:"huán jìng", meaning:"environment", literal:"boundary + boundary (environment)" },
  { hanzi:"还是", pinyin:"hái shì", meaning:"still / or", literal:"still/also + to be" },
  { hanzi:"活动", pinyin:"huó dòng", meaning:"activity", literal:"live + move" },
  { hanzi:"火锅", pinyin:"huǒ guō", meaning:"hot pot", literal:"fire + pot" },
  { hanzi:"或者", pinyin:"huò zhě", meaning:"or", literal:"or + one who/-er" },
  { hanzi:"机会", pinyin:"jī huì", meaning:"opportunity", literal:"machine/opportunity + can/meeting" },
  { hanzi:"积极", pinyin:"jī jí", meaning:"active / positive", literal:"accumulate + extreme" },
  { hanzi:"基础", pinyin:"jī chǔ", meaning:"foundation / basics", literal:"foundation + foundation stone" },
  { hanzi:"计划", pinyin:"jì huà", meaning:"plan", literal:"count/plan + plan/stroke" },
  { hanzi:"记得", pinyin:"jì de", meaning:"to remember", literal:"record/remember + get/obtain" },
  { hanzi:"记者", pinyin:"jì zhě", meaning:"journalist", literal:"record/remember + one who/-er" },
  { hanzi:"季节", pinyin:"jì jié", meaning:"season", literal:"season + festival/joint" },
  { hanzi:"既然", pinyin:"jì rán", meaning:"since (given that)", literal:"since/already + so/thus" },
  { hanzi:"技术", pinyin:"jì shù", meaning:"technology / skill", literal:"skill + technique" },
  { hanzi:"加班", pinyin:"jiā bān", meaning:"to work overtime", literal:"add + class/shift" },
  { hanzi:"加油", pinyin:"jiā yóu", meaning:"to cheer on / to refuel", literal:"add + oil" },
  { hanzi:"价格", pinyin:"jià gé", meaning:"price", literal:"price + standard/grid" },
  { hanzi:"坚持", pinyin:"jiān chí", meaning:"to persist", literal:"firm + hold/maintain" },
  { hanzi:"检查", pinyin:"jiǎn chá", meaning:"to check", literal:"inspect + check" },
  { hanzi:"简单", pinyin:"jiǎn dān", meaning:"simple", literal:"simple + single/list" },
  { hanzi:"建议", pinyin:"jiàn yì", meaning:"suggestion", literal:"build/establish + discuss/opinion" },
  { hanzi:"健康", pinyin:"jiàn kāng", meaning:"health", literal:"healthy + healthy" },
  { hanzi:"讲", pinyin:"jiǎng", meaning:"to speak / to explain" },
  { hanzi:"交", pinyin:"jiāo", meaning:"to hand in / to make (friends)" },
  { hanzi:"交通", pinyin:"jiāo tōng", meaning:"traffic", literal:"hand over/associate + through/connect" },
  { hanzi:"骄傲", pinyin:"jiāo ào", meaning:"proud", literal:"proud + proud" },
  { hanzi:"角", pinyin:"jiǎo", meaning:"corner" },
  { hanzi:"接", pinyin:"jiē", meaning:"to receive / to pick up" },
  { hanzi:"接受", pinyin:"jiē shòu", meaning:"to accept", literal:"receive/connect + receive/endure" },
  { hanzi:"街道", pinyin:"jiē dào", meaning:"street", literal:"street + path/way" },
  { hanzi:"节目", pinyin:"jié mù", meaning:"program / show", literal:"festival/joint + eye/item" },
  { hanzi:"节日", pinyin:"jié rì", meaning:"festival / holiday", literal:"festival/joint + day/sun" },
  { hanzi:"结果", pinyin:"jié guǒ", meaning:"result", literal:"tie/结knot + fruit/result" },
  { hanzi:"结婚", pinyin:"jié hūn", meaning:"to get married", literal:"tie/结knot + marriage" },
  { hanzi:"结束", pinyin:"jié shù", meaning:"to end", literal:"tie/结knot + bind/end" },
  { hanzi:"解决", pinyin:"jiě jué", meaning:"to solve", literal:"untie/explain + decide" },
  { hanzi:"解释", pinyin:"jiě shì", meaning:"to explain", literal:"untie/explain + release/explain" },
  { hanzi:"借", pinyin:"jiè", meaning:"to borrow / to lend" },
  { hanzi:"经常", pinyin:"jīng cháng", meaning:"often", literal:"pass through/classic + often" },
  { hanzi:"经过", pinyin:"jīng guò", meaning:"to pass by / through", literal:"pass through/classic + pass" },
  { hanzi:"经理", pinyin:"jīng lǐ", meaning:"manager", literal:"pass through/classic + reason/manage" },
  { hanzi:"经验", pinyin:"jīng yàn", meaning:"experience", literal:"pass through/classic + test/examine" },
  { hanzi:"精彩", pinyin:"jīng cǎi", meaning:"wonderful", literal:"refined/essence + color/splendor" },
  { hanzi:"景色", pinyin:"jǐng sè", meaning:"scenery", literal:"scenery + color" },
  { hanzi:"警察", pinyin:"jǐng chá", meaning:"police", literal:"alert/police + observe" },
  { hanzi:"竟然", pinyin:"jìng rán", meaning:"unexpectedly", literal:"unexpectedly + so/thus" },
  { hanzi:"竞争", pinyin:"jìng zhēng", meaning:"competition", literal:"compete + contend" },
  { hanzi:"镜子", pinyin:"jìng zi", meaning:"mirror", literal:"mirror/lens + (noun suffix)" },
  { hanzi:"究竟", pinyin:"jiū jìng", meaning:"after all", literal:"investigate + unexpectedly" },
  { hanzi:"举行", pinyin:"jǔ xíng", meaning:"to hold (an event)", literal:"lift/hold + walk/OK" },
  { hanzi:"拒绝", pinyin:"jù jué", meaning:"to refuse", literal:"refuse + cut off/absolutely" },
  { hanzi:"聚会", pinyin:"jù huì", meaning:"gathering / party", literal:"gather + can/meeting" },
  { hanzi:"决定", pinyin:"jué dìng", meaning:"to decide", literal:"decide + fix/decide" },
  { hanzi:"咖啡厅", pinyin:"kā fēi tīng", meaning:"cafe", literal:"phonetic loanword (coffee) + hall" },
  { hanzi:"开心", pinyin:"kāi xīn", meaning:"happy", literal:"open + heart" },
  { hanzi:"开玩笑", pinyin:"kāi wán xiào", meaning:"to joke", literal:"open + play + laugh" },
  { hanzi:"看法", pinyin:"kàn fǎ", meaning:"viewpoint", literal:"look + law/method" },
  { hanzi:"考虑", pinyin:"kǎo lǜ", meaning:"to consider", literal:"test/examine + consider" },
  { hanzi:"科学", pinyin:"kē xué", meaning:"science", literal:"branch of study + study" },
  { hanzi:"棵", pinyin:"kē", meaning:"(measure word for trees)" },
  { hanzi:"礼貌", pinyin:"lǐ mào", meaning:"politeness", literal:"ceremony + appearance" },
];
